import { randomUUID } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { Pool } from 'pg';
import { OperatorService } from '../services/operator-service';
import { DestinationService, ContentService } from '../services/content-service';
import { PublicVisitorService } from '../services/public-visitor-service';
import { IntelligenceService } from '../services/intelligence-service';
import { AiConciergeService } from '../services/ai-concierge-service';
import { requirePermission, requireProvinceAccess, requireOperatorAccess } from '../auth/authorization';
import type { ComplianceStatus, ProvinceCode, PublicationStatus, ContentItem } from '../domain/types';
import type { MetricPeriod } from '../domain/intelligence';
import type { AiConversationRequest } from '../domain/ai';
import { PostgresAuditRepository, PostgresContentRepository, PostgresDestinationRepository, PostgresOperatorRepository, PostgresProvinceRepository } from '../persistence/postgres-repositories';
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const repositories={operators:new PostgresOperatorRepository(pool),destinations:new PostgresDestinationRepository(pool),content:new PostgresContentRepository(pool),provinces:new PostgresProvinceRepository(pool),audit:new PostgresAuditRepository(pool)};
const operatorService=new OperatorService(repositories.operators,repositories.audit);const destinationService=new DestinationService(repositories.destinations,repositories.audit);const contentService=new ContentService(repositories.content,repositories.audit);const publicVisitorService=new PublicVisitorService(repositories);const intelligenceService=new IntelligenceService(repositories);const aiConciergeService=new AiConciergeService(repositories);
export function createApiServer(){return createServer(async(req,res)=>{const requestId=req.headers['x-request-id']?.toString()||randomUUID();res.setHeader('x-request-id',requestId);res.setHeader('content-type','application/json; charset=utf-8');try{const url=new URL(req.url||'/','http://localhost');
if(req.method==='GET'&&url.pathname==='/api/v1/public/destinations'){const p=parseProvince(url.searchParams.get('province'));return send(res,200,{data:await publicVisitorService.destinationsList({provinceCode:p,cursor:url.searchParams.get('cursor')||undefined}),requestId});}
if(req.method==='GET'&&url.pathname.startsWith('/api/v1/public/destinations/'))return send(res,200,{data:await publicVisitorService.destination(url.pathname.split('/').pop()!),requestId});
if(req.method==='GET'&&url.pathname==='/api/v1/public/content'){const type=(url.searchParams.get('type') as ContentItem['type'])||undefined;return send(res,200,{data:await publicVisitorService.contentList({type,cursor:url.searchParams.get('cursor')||undefined}),requestId});}
if(req.method==='GET'&&url.pathname.startsWith('/api/v1/public/content/'))return send(res,200,{data:await publicVisitorService.content(url.pathname.split('/').pop()!),requestId});
if(req.method==='GET'&&url.pathname==='/api/v1/public/operators'){const p=parseProvince(url.searchParams.get('province'));return send(res,200,{data:await publicVisitorService.operatorsList({provinceCode:p,cursor:url.searchParams.get('cursor')||undefined}),requestId});}
if(req.method==='GET'&&url.pathname.startsWith('/api/v1/public/operators/'))return send(res,200,{data:await publicVisitorService.operator(url.pathname.split('/').pop()!),requestId});
const context=authenticate(req,requestId);
if(req.method==='POST'&&url.pathname==='/api/v1/ai/concierge'){const body=await readJson(req);if(typeof body.message!=='string')throwValidation('message is required');if(body.message.length>4000)throwValidation('message exceeds maximum length');const provinceCode=body.provinceCode===undefined?undefined:parseProvince(body.provinceCode);const data=await aiConciergeService.answer({message:body.message,sessionId:typeof body.sessionId==='string'?body.sessionId:undefined,...(provinceCode?{provinceCode}: {})} satisfies AiConversationRequest);return send(res,200,{data,requestId});}
if(req.method==='GET'&&url.pathname==='/api/v1/intelligence/report'){requirePermission(context,'intelligence:read');const period=(url.searchParams.get('period') as MetricPeriod)||'month';if(!['day','week','month','quarter','year'].includes(period))throwValidation('Invalid reporting period');return send(res,200,{data:await intelligenceService.report(period),requestId});}
if(req.method==='GET'&&url.pathname==='/api/v1/intelligence/provinces'){requirePermission(context,'intelligence:read');const period=(url.searchParams.get('period') as MetricPeriod)||'month';if(!['day','week','month','quarter','year'].includes(period))throwValidation('Invalid reporting period');return send(res,200,{data:await intelligenceService.provincial(period),requestId});}
if(req.method==='GET'&&url.pathname==='/api/v1/intelligence/snapshot'){requirePermission(context,'intelligence:read');const period=(url.searchParams.get('period') as MetricPeriod)||'month';if(!['day','week','month','quarter','year'].includes(period))throwValidation('Invalid reporting period');return send(res,200,{data:await intelligenceService.snapshot(period),requestId});}
if(req.method==='GET'&&url.pathname==='/api/v1/operators'){requirePermission(context,'operator:read');const provinceCode=parseProvince(url.searchParams.get('province'));if(provinceCode)requireProvinceAccess(context,provinceCode);return send(res,200,{data:await repositories.operators.list({provinceCode,status:url.searchParams.get('status')||undefined,cursor:url.searchParams.get('cursor')||undefined}),requestId});}
if(req.method==='POST'&&url.pathname==='/api/v1/operators'){requirePermission(context,'operator:register');const b=await readJson(req);if(typeof b.legalName!=='string'||typeof b.provinceCode!=='string')throwValidation('legalName and provinceCode are required');const provinceCode=parseProvince(b.provinceCode);if(!provinceCode)throwValidation('provinceCode is required');requireProvinceAccess(context,provinceCode);const data=await operatorService.register({legalName:b.legalName,tradingName:typeof b.tradingName==='string'?b.tradingName:undefined,provinceCode,actorId:context.user.id,requestId});return send(res,201,{data,requestId});}
if(url.pathname.startsWith('/api/v1/operators/')){const [id,action]=url.pathname.slice('/api/v1/operators/'.length).split('/');if(!id)return send(res,404,{error:{code:'NOT_FOUND',message:'Operator route not found'},requestId});if(req.method==='GET'&&!action){requirePermission(context,'operator:read');requireOperatorAccess(context,id);return send(res,200,{data:await operatorService.get(id),requestId});}if(req.method==='POST'&&action){const o=await operatorService.get(id);requireProvinceAccess(context,o.provinceCode);const b=await readJson(req);if(action==='approve'){requirePermission(context,'operator:approve');return send(res,200,{data:await operatorService.approve(id,context.user.id,requestId),requestId});}if(action==='reject'){requirePermission(context,'operator:approve');return send(res,200,{data:await operatorService.reject(id,requiredString(b.reason,'reason'),context.user.id,requestId),requestId});}if(action==='compliance'){requirePermission(context,'operator:manage_compliance');if(typeof b.status!=='string')throwValidation('status is required');return send(res,200,{data:await operatorService.updateCompliance(id,b.status as ComplianceStatus,typeof b.note==='string'?b.note:undefined,context.user.id,requestId),requestId});}if(action==='suspend'){requirePermission(context,'operator:manage_status');return send(res,200,{data:await operatorService.suspend(id,requiredString(b.reason,'reason'),context.user.id,requestId),requestId});}if(action==='close'){requirePermission(context,'operator:manage_status');return send(res,200,{data:await operatorService.close(id,requiredString(b.reason,'reason'),context.user.id,requestId),requestId});}}
}
if(req.method==='GET'&&url.pathname==='/api/v1/provinces')return send(res,200,{data:await repositories.provinces.list(),requestId});
if(req.method==='GET'&&url.pathname==='/api/v1/destinations'){requirePermission(context,'content:read');const p=parseProvince(url.searchParams.get('province'));if(p)requireProvinceAccess(context,p);return send(res,200,{data:await destinationService.list({provinceCode:p,cursor:url.searchParams.get('cursor')||undefined}),requestId});}
if(req.method==='GET'&&url.pathname.startsWith('/api/v1/destinations/')){requirePermission(context,'content:read');const id=url.pathname.split('/').pop()!;const d=await destinationService.get(id);requireProvinceAccess(context,d.provinceCode);return send(res,200,{data:d,requestId});}
if(req.method==='POST'&&url.pathname==='/api/v1/destinations'){requirePermission(context,'content:write');const b=await readJson(req);if(typeof b.name!=='string'||typeof b.slug!=='string'||typeof b.provinceCode!=='string')throwValidation('name, slug and provinceCode are required');const provinceCode=parseProvince(b.provinceCode);if(!provinceCode)throwValidation('provinceCode is required');requireProvinceAccess(context,provinceCode);const d=await destinationService.create({name:b.name,slug:b.slug,provinceCode,description:typeof b.description==='string'?b.description:undefined,latitude:typeof b.latitude==='number'?b.latitude:undefined,longitude:typeof b.longitude==='number'?b.longitude:undefined,actorId:context.user.id,requestId});return send(res,201,{data:d,requestId});}
if(req.method==='GET'&&url.pathname==='/api/v1/content'){requirePermission(context,'content:read');return send(res,200,{data:await contentService.list({type:(url.searchParams.get('type') as ContentItem['type'])||undefined,publicationStatus:(url.searchParams.get('status') as PublicationStatus)||undefined,provinceCode:parseProvince(url.searchParams.get('province')),cursor:url.searchParams.get('cursor')||undefined}),requestId});}
if(req.method==='GET'&&url.pathname.startsWith('/api/v1/content/')){requirePermission(context,'content:read');return send(res,200,{data:await contentService.get(url.pathname.split('/').pop()!),requestId});}
if(req.method==='POST'&&url.pathname==='/api/v1/content'){requirePermission(context,'content:write');const b=await readJson(req);if(typeof b.type!=='string'||typeof b.title!=='string'||typeof b.slug!=='string')throwValidation('type, title and slug are required');if(!['destination','attraction','experience','event','operator','campaign'].includes(b.type))throwValidation('Invalid content type');const provinceCode=b.provinceCode===undefined?undefined:parseProvince(b.provinceCode);const item=await contentService.create({type:b.type as ContentItem['type'],title:b.title,slug:b.slug,...(provinceCode?{provinceCode}:{}),actorId:context.user.id,requestId});return send(res,201,{data:item,requestId});}
if(req.method==='POST'&&url.pathname.match(/^\/api\/v1\/content\/[^/]+\/publish$/)){requirePermission(context,'content:publish');const id=url.pathname.split('/')[4];return send(res,200,{data:await contentService.setPublication(id,'published',context.user.id,requestId),requestId});}
return send(res,404,{error:{code:'NOT_FOUND',message:'Route not found'},requestId});}catch(e:any){const status=e?.code==='UNAUTHORIZED'?401:e?.code==='FORBIDDEN'?403:e?.code==='NOT_FOUND'?404:e?.code==='VALIDATION_ERROR'?400:e?.code==='CONFLICT'?409:500;return send(res,status,{error:{code:e?.code||'INTERNAL_ERROR',message:status===500?'Internal server error':e.message},requestId});}});}
function parseProvince(value:unknown):ProvinceCode|undefined{if(value===undefined||value===null||value==='')return undefined;if(typeof value!=='string'||!['NCD','CENTRAL','GULF','MILNE_BAY','ORO','MOROBE','MADANG','EAST_SEPIK','WEST_SEPIK','MANUS','NEW_IRELAND','EAST_NEW_BRITAIN','WEST_NEW_BRITAIN','BOUGAINVILLE','ENGA','EASTERN_HIGHLANDS','SIMBU','WESTERN_HIGHLANDS','SOUTHERN_HIGHLANDS','JIWAKA','HELA','WESTERN'].includes(value))throwValidation('Invalid province code');return value as ProvinceCode;}
function authenticate(req:IncomingMessage,requestId:string){const subject=req.headers.authorization?.replace(/^Bearer\s+/i,'')||(process.env.NODE_ENV!=='production'?process.env.DEV_IDENTITY_SUBJECT:undefined);if(!subject){const e:any=new Error('Authentication required');e.code='UNAUTHORIZED';throw e;}const roles=(process.env.DEV_IDENTITY_ROLES||'platform_admin').split(',').map(r=>r.trim()).filter(Boolean);return{user:{id:process.env.DEV_IDENTITY_USER_ID||'00000000-0000-0000-0000-000000000001',externalSubject:subject,email:process.env.DEV_IDENTITY_EMAIL||'developer@pngtourism.local',displayName:'Development User',roles:roles as any},requestId};}
function requiredString(v:unknown,f:string){if(typeof v!=='string'||!v.trim())throwValidation(`${f} is required`);return v;}function throwValidation(message:string):never{const e:any=new Error(message);e.code='VALIDATION_ERROR';throw e;}async function readJson(req:IncomingMessage){const chunks:Buffer[]=[];for await(const c of req)chunks.push(Buffer.from(c));try{const p:unknown=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!p||typeof p!=='object'||Array.isArray(p))throw new Error();return p as Record<string,unknown>;}catch{throwValidation('Invalid JSON body');}}function send(res:ServerResponse,status:number,body:unknown){res.statusCode=status;res.end(JSON.stringify(body));}
