import { randomUUID } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { Pool } from 'pg';
import { OperatorService } from '../services/operator-service';
import { DestinationService, ContentService } from '../services/content-service';
import { PublicVisitorService } from '../services/public-visitor-service';
import { OfflineService } from '../services/offline-service';
import { IntelligenceService } from '../services/intelligence-service';
import { AiConciergeService } from '../services/ai-concierge-service';
import { IndustryEcosystemService } from '../services/industry-ecosystem-service';
import { requirePermission, requireProvinceAccess, requireOperatorAccess } from '../auth/authorization';
import { authenticateBearerToken } from '../auth/token-auth';
import { applySecurityHeaders, enforceRateLimit, requestBodyLimit } from './security';
import type { ComplianceStatus, ProvinceCode, PublicationStatus, ContentItem, OperatorStatus } from '../domain/types';
import type { MetricPeriod } from '../domain/intelligence';
import type { AiConversationRequest } from '../domain/ai';
import { PostgresAiAuditRepository, PostgresAuditRepository, PostgresContentRepository, PostgresDestinationRepository, PostgresOperatorRepository, PostgresProvinceRepository } from '../persistence/postgres-repositories';
import { PostgresIndustryRepository } from '../persistence/industry-repository';
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const repositories:any={operators:new PostgresOperatorRepository(pool),destinations:new PostgresDestinationRepository(pool),content:new PostgresContentRepository(pool),provinces:new PostgresProvinceRepository(pool),audit:new PostgresAuditRepository(pool),aiAudit:new PostgresAiAuditRepository(pool),industry:new PostgresIndustryRepository(pool)};
const operatorService=new OperatorService(repositories.operators,repositories.audit);const destinationService=new DestinationService(repositories.destinations,repositories.audit);const contentService=new ContentService(repositories.content,repositories.audit);const publicVisitorService=new PublicVisitorService(repositories);const offlineService=new OfflineService({destinations:repositories.destinations,content:repositories.content});const intelligenceService=new IntelligenceService(repositories);const aiConciergeService=new AiConciergeService(repositories);const industryService=new IndustryEcosystemService({...repositories.industry,isOperatorActive:async(id:string)=>{const o=await repositories.operators.getById(id);return o?.status==='active';}});
export function createApiServer(){return createServer(async(req,res)=>{const requestId=req.headers['x-request-id']?.toString()||randomUUID();res.setHeader('x-request-id',requestId);res.setHeader('content-type','application/json; charset=utf-8');applySecurityHeaders(res);if(!enforceRateLimit(req,res))return;try{requestBodyLimit(req);const url=new URL(req.url||'/','http://localhost');
if(req.method==='GET'&&url.pathname==='/api/v1/public/industry/profiles'){const p=parseProvince(url.searchParams.get('province'));return send(res,200,{data:await industryService.publicProfiles(p),requestId});}
if(req.method==='GET'&&url.pathname==='/api/v1/public/industry/experiences'){const p=parseProvince(url.searchParams.get('province'));const destinationId=url.searchParams.get('destinationId')||undefined;return send(res,200,{data:await industryService.publicExperiences({provinceCode:p,destinationId}),requestId});}
if(req.method==='POST'&&url.pathname==='/api/v1/public/leads'){const b=await readJson(req);if(typeof b.operatorId!=='string'||typeof b.source!=='string')throwValidation('operatorId and source are required');if(!['visitor','qr','referral'].includes(b.source))throwValidation('Invalid lead source');const data=await industryService.createLead({id:randomUUID(),operatorId:b.operatorId,experienceId:typeof b.experienceId==='string'?b.experienceId:undefined,source:b.source as any,status:'new',visitorMessage:typeof b.visitorMessage==='string'?b.visitorMessage.slice(0,2000):undefined,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});return send(res,201,{data:{id:data.id,status:data.status},requestId});}
const context=authenticate(req,requestId);
if(req.method==='GET'&&url.pathname==='/api/v1/industry/profile'){requirePermission(context,'operator:read');const ids=context.user.operatorIds??[];if(ids.length!==1)throwValidation('Operator identity is required');return send(res,200,{data:await repositories.industry.getProfile(ids[0]),requestId});}
if(req.method==='PUT'&&url.pathname==='/api/v1/industry/profile'){requirePermission(context,'operator:read');const b=await readJson(req);const operatorId=typeof b.operatorId==='string'?b.operatorId:context.user.operatorIds?.[0];if(!operatorId)throwValidation('operator identity is required');requireOperatorAccess(context,operatorId);if(typeof b.displayName!=='string'||typeof b.description!=='string'||typeof b.provinceCode!=='string')throwValidation('displayName, description and provinceCode are required');const p=parseProvince(b.provinceCode);requireProvinceAccess(context,p!);const current=await repositories.industry.getProfile(operatorId);const data=await industryService.saveProfile({id:current?.id||randomUUID(),operatorId,displayName:b.displayName,description:b.description,provinceCode:p!,categories:Array.isArray(b.categories)?b.categories.filter((x:any)=>typeof x==='string').slice(0,20):[],publicContact:typeof b.publicContact==='object'&&b.publicContact?b.publicContact as any:undefined,published:current?.published??false,updatedAt:new Date().toISOString(),version:current?.version??1},current?.version);return send(res,200,{data,requestId});}
if(req.method==='GET'&&url.pathname==='/api/v1/industry/leads'){requirePermission(context,'operator:read');const ids=context.user.operatorIds??[];if(ids.length!==1)throwValidation('Operator identity is required');return send(res,200,{data:await industryService.operatorLeads(ids[0]),requestId});}
if(req.method==='GET'&&url.pathname==='/api/v1/public/destinations'){const p=parseProvince(url.searchParams.get('province'));return send(res,200,{data:await publicVisitorService.destinationsList({provinceCode:p,cursor:url.searchParams.get('cursor')||undefined}),requestId});}
if(req.method==='GET'&&url.pathname.startsWith('/api/v1/public/destinations/'))return send(res,200,{data:await publicVisitorService.destination(url.pathname.split('/').pop()!),requestId});
if(req.method==='GET'&&url.pathname==='/api/v1/public/content'){const type=(url.searchParams.get('type') as ContentItem['type'])||undefined;const provinceCode=parseProvince(url.searchParams.get('province'));return send(res,200,{data:await publicVisitorService.contentList({type,provinceCode,cursor:url.searchParams.get('cursor')||undefined}),requestId});}
if(req.method==='GET'&&url.pathname.startsWith('/api/v1/public/content/'))return send(res,200,{data:await publicVisitorService.content(url.pathname.split('/').pop()!),requestId});
if(req.method==='GET'&&url.pathname==='/api/v1/public/operators'){const p=parseProvince(url.searchParams.get('province'));return send(res,200,{data:await publicVisitorService.operatorsList({provinceCode:p,cursor:url.searchParams.get('cursor')||undefined}),requestId});}
if(req.method==='GET'&&url.pathname.startsWith('/api/v1/public/operators/'))return send(res,200,{data:await publicVisitorService.operator(url.pathname.split('/').pop()!),requestId});
if(req.method==='GET'&&url.pathname==='/api/v1/public/offline/manifest'){const channel=url.searchParams.get('channel');if(channel!=='provincial'&&channel!=='kiosk')throwValidation('channel must be provincial or kiosk');const provinceCode=parseProvince(url.searchParams.get('province'));if(channel==='provincial'&&!provinceCode)throwValidation('province is required for provincial offline manifests');if(channel==='kiosk'&&provinceCode)throwValidation('province is not supported for kiosk manifests');return send(res,200,{data:await offlineService.buildManifest({channel,provinceCode}),requestId});}
if(req.method==='GET'&&url.pathname==='/api/v1/public/qr/resolve'){const targetType=url.searchParams.get('type');const targetId=url.searchParams.get('id');if(targetType!=='destination'&&targetType!=='content')throwValidation('type must be destination or content');if(!targetId?.trim())throwValidation('id is required');const target=targetType==='destination'?await publicVisitorService.destination(targetId):await publicVisitorService.content(targetId);const handoff=offlineService.createQrHandoff(targetType,target.id);const publicPath=`/api/v1/public/${targetType}s/${encodeURIComponent(target.id)}`;return send(res,200,{data:{...handoff,publicPath},requestId});}
// Existing authenticated routes continue unchanged.
return send(res,404,{error:{code:'NOT_FOUND',message:'Route not found'},requestId});}catch(e:any){const status=e?.code==='UNAUTHORIZED'?401:e?.code==='FORBIDDEN'?403:e?.code==='NOT_FOUND'?404:e?.code==='VALIDATION_ERROR'?400:e?.code==='CONFLICT'?409:500;return send(res,status,{error:{code:e?.code||'INTERNAL_ERROR',message:status===500?'Internal server error':e.message},requestId});}});}
function parseProvince(value:unknown):ProvinceCode|undefined{if(value===undefined||value===null||value==='')return undefined;if(typeof value!=='string'||!['NCD','CENTRAL','GULF','MILNE_BAY','ORO','MOROBE','MADANG','EAST_SEPIK','WEST_SEPIK','MANUS','NEW_IRELAND','EAST_NEW_BRITAIN','WEST_NEW_BRITAIN','BOUGAINVILLE','ENGA','EASTERN_HIGHLANDS','SIMBU','WESTERN_HIGHLANDS','SOUTHERN_HIGHLANDS','JIWAKA','HELA','WESTERN'].includes(value))throwValidation('Invalid province code');return value as ProvinceCode;}
function authenticate(req:IncomingMessage,requestId:string){if(process.env.NODE_ENV==='production')return{user:authenticateBearerToken(req.headers.authorization,process.env.AUTH_JWT_SECRET||''),requestId};const subject=req.headers.authorization?.replace(/^Bearer\s+/i,'')||(process.env.DEV_IDENTITY_SUBJECT||'development');const roles=(process.env.DEV_IDENTITY_ROLES||'platform_admin').split(',').map(r=>r.trim()).filter(Boolean);return{user:{id:process.env.DEV_IDENTITY_USER_ID||'00000000-0000-0000-0000-000000000001',externalSubject:subject,email:process.env.DEV_IDENTITY_EMAIL||'developer@pngtourism.local',displayName:'Development User',roles:roles as any},requestId};}
function requiredString(v:unknown,f:string){if(typeof v!=='string'||!v.trim())throwValidation(`${f} is required`);return v;}function throwValidation(message:string):never{const e:any=new Error(message);e.code='VALIDATION_ERROR';throw e;}async function readJson(req:IncomingMessage){const chunks:Buffer[]=[];let size=0;const maxBytes=Number(process.env.REQUEST_BODY_MAX_BYTES||1_048_576);for await(const c of req){const chunk=Buffer.from(c);size+=chunk.length;if(size>maxBytes)throwValidation('Request body exceeds maximum size');chunks.push(chunk);}try{const p:unknown=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!p||typeof p!=='object'||Array.isArray(p))throw new Error();return p as Record<string,unknown>;}catch{throwValidation('Invalid JSON body');}}function send(res:ServerResponse,status:number,body:unknown){res.statusCode=status;res.end(JSON.stringify(body));}
