import { createApiServer } from './api';
import { handleIndustryApi } from './industry-api';
import { handleOperatorRegistrationApi } from './operator-registration-api';
import { handleVisitorEngagementApi } from './visitor-engagement-api';
import { handlePassportApi } from './passport-api';
import { handleCommandCentreApi } from './command-centre-api';
import { handleCampaignEventApi } from './campaign-event-api';
import { handleContentStudioApi } from './content-studio-api';
import { handleDestinationPublicApi } from './destination-public-api';
import { handleMediaApi } from './media-api';
import { handleNtdpEnterpriseApi } from './ntdp-enterprise-api';
import { handleNtdpRegulatoryApi } from './ntdp-regulatory-api';
import { applyCors } from './security';
import { healthResponse } from './health';
const port=Number(process.env.PORT||3000);const server=createApiServer();const existingHandler=server.listeners('request')[0] as (req:import('node:http').IncomingMessage,res:import('node:http').ServerResponse)=>void;server.removeListener('request',existingHandler);server.on('request',async(req,res)=>{if(!applyCors(req,res))return;if(req.method==='GET'&&new URL(req.url||'/','http://localhost').pathname==='/health'){res.statusCode=200;res.setHeader('content-type','application/json; charset=utf-8');res.end(JSON.stringify(healthResponse()));return;}if(await handleNtdpRegulatoryApi(req,res))return;if(await handleNtdpEnterpriseApi(req,res))return;if(await handleOperatorRegistrationApi(req,res))return;if(await handleIndustryApi(req,res))return;if(await handleVisitorEngagementApi(req,res))return;if(await handlePassportApi(req,res))return;if(await handleCommandCentreApi(req,res))return;if(await handleCampaignEventApi(req,res))return;if(await handleContentStudioApi(req,res))return;if(await handleDestinationPublicApi(req,res))return;if(await handleMediaApi(req,res))return;existingHandler(req,res)});server.listen(port,'0.0.0.0',()=>console.log(`PNG Tourism Platform API listening on :${port}`));
