import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { PostgresMediaRepository } from '../persistence/media-repository';
import { authenticateBearerToken } from '../auth/token-auth';
import { requirePermission, requireProvinceAccess } from '../auth/authorization';
import { applySecurityHeaders, enforceRateLimit, requestBodyLimit } from './security';
import type { MediaKind } from '../domain/content-studio';
import type { ProvinceCode, PublicationStatus } from '../domain/types';
const pool=new Pool({connectionString:process.env.DATABASE_URL});const repo=new PostgresMediaRepository(pool);
export async function handleMediaApi(req:IncomingMessage,res:ServerResponse):Promise<boolean>{const url=new URL(req.url||'/','http://localhost');if(!url.pathname.startsWith('/api/v1/content-studio/media'))return false;const requestId=req.headers['x-request-id']?.toString()||randomUUID();res.setHeader('x-request-id',requestId);res.setHeader('content-type','application/json; charset=utf-8');applySecurityHeaders(res);try{requestBodyLimit(req);if(!enforceRateLimit(req,res))return true;const context=auth(req,requestId);requirePermission(context,'content:write');const match=url.pathname.match(/^\/api\/v1\/content-studio\/media\/([^/]+)\/publish$/);if(req.method==='POST'&&match){requirePermission(context,'content:publish');const updated=await repo.setPublication(decodeURIComponent(match[1]),'published');if(!updated)return send(res,404,{error:{code:'NOT_FOUND',message:'Media asset not found'},requestId});if(updated.provinceCode)requireProvinceAccess(context,updated.provinceCode);return send(res,200,{data:updated,requestId});}if(req.method==='POST'&&url.pathname==='/api/v1/content-studio/media'){const b=await readJson(req);if(typeof b.storageKey!=='string'||typeof b.altText!=='string'||typeof b.mimeType!=='string'||!['image','video','document'].includes(String(b.kind)))return send(res,400,{error:{code:'VALIDATION_ERROR',message:'kind, storageKey, altText and mimeType are required'},requestId});const province=b.provinceCode as ProvinceCode|undefined;if(province)requireProvinceAccess(context,province);const asset=await repo.create({kind:b.kind as MediaKind,storageKey:b.storageKey,publicUrl:typeof b.publicUrl==='string'?b.publicUrl:undefined,altText:b.altText,caption:typeof b.caption==='string'?b.caption:undefined,width:typeof b.width==='number'?b.width:undefined,height:typeof b.height==='number'?b.height:undefined,mimeType:b.mimeType,byteSize:typeof b.byteSize==='number'?b.byteSize:undefined,checksum:typeof b.checksum==='string'?b.checksum:undefined,provinceCode:province,publicationStatus:'draft',version:1});return send(res,201,{data:asset,requestId});}return send(res,404,{error:{code:'NOT_FOUND',message:'Media route not found'},requestId});}catch(e:any){const status=e?.code==='UNAUTHORIZED'?401:e?.code==='FORBIDDEN'?403:e?.code==='NOT_FOUND'?404:e?.code==='VALIDATION_ERROR'?400:500;return send(res,status,{error:{code:e?.code||'INTERNAL_ERROR',message:status===500?'Internal server error':e.message},requestId});}}
function auth(req:IncomingMessage,requestId:string){if(process.env.NODE_ENV==='production')return{user:authenticateBearerToken(req.headers.authorization,process.env.AUTH_JWT_SECRET||''),requestId};const roles=(process.env.DEV_IDENTITY_ROLES||'platform_admin').split(',').map(r=>r.trim()).filter(Boolean);return{user:{id:process.env.DEV_IDENTITY_USER_ID||'00000000-0000-0000-0000-000000000001',externalSubject:'development',email:'developer@pngtourism.local',displayName:'Development User',roles:roles as any},requestId};}async function readJson(req:IncomingMessage){const chunks:Buffer[]=[];for await(const c of req)chunks.push(Buffer.from(c));try{const p=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!p||typeof p!=='object'||Array.isArray(p))throw new Error();return p as Record<string,any>}catch{const e:any=new Error('Invalid JSON body');e.code='VALIDATION_ERROR';throw e;}}function send(res:ServerResponse,status:number,body:unknown){res.statusCode=status;res.end(JSON.stringify(body));return true;}
