import { readJson } from './request-body';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { requirePermission, requireProvinceAccess } from '../auth/authorization';
import { authenticate } from './api';
import { NtdpCoreService } from '../services/ntdp-core-service';
import { requireAuthority, requireOwnedOperator, requireOwnedResource, requireOperatorFilter, requireProvinceFilter } from './resource-access';
import type { ProvinceCode } from '../domain/types';
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const service = new NtdpCoreService(pool);
export async function handleNtdpEnterpriseApi(req: IncomingMessage, res: ServerResponse): Promise<boolean> {
  const url = new URL(req.url || '/', 'http://localhost'); if (!url.pathname.startsWith('/api/v1/ntdp/')) return false;
  try {
    const context = await authenticate(req, req.headers['x-request-id']?.toString() || randomUUID());
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/warehouse/operator-snapshot') { requirePermission(context,'warehouse:write'); return send(res,200,{data:await service.snapshotOperators(),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/warehouse/operator-snapshot') { requirePermission(context,'warehouse:write'); const b=await readJson(req); return send(res,200,{data:await service.snapshotOperators(typeof b.snapshotDate==='string'?b.snapshotDate:undefined),requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/warehouse/metrics') { requirePermission(context,'warehouse:read'); const p=parseProvince(url.searchParams.get('province')); requireProvinceFilter(context,p); return send(res,200,{data:await service.dailyMetrics(url.searchParams.get('metricCode')||undefined,p,url.searchParams.get('from')||undefined,url.searchParams.get('to')||undefined),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/warehouse/metrics/refresh') { requirePermission(context,'warehouse:write'); const b=await readJson(req); return send(res,200,{data:await service.refreshDailyMetrics(typeof b.runDate==='string'?b.runDate:undefined),requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/warehouse/etl-runs') { requirePermission(context,'warehouse:read'); const limit=Number(url.searchParams.get('limit')||50); return send(res,200,{data:await service.warehouseEtlRuns(Number.isFinite(limit)?limit:50),requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/gis/layers') { requirePermission(context,'gis:read'); return send(res,200,{data:await service.geoLayers(),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/gis/sync') { requirePermission(context,'gis:write'); requireAuthority(context); return send(res,200,{data:await service.syncRegistryGeoAssets(),requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/gis/assets') { requirePermission(context,'gis:read'); const p=parseProvince(url.searchParams.get('province')); requireProvinceFilter(context,p); return send(res,200,{data:await service.geoAssets(p,url.searchParams.get('layer')||undefined,context.user.roles.includes('operator')||url.searchParams.get('publicOnly')==='true'),requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/gis/geojson') { requirePermission(context,'gis:read'); const p=parseProvince(url.searchParams.get('province')); requireProvinceFilter(context,p); return send(res,200,{data:await service.geoJsonAssets(p,url.searchParams.get('layer')||undefined),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/gis/assets') { requirePermission(context,'gis:write'); requireAuthority(context); const b=await readJson(req); const p=parseProvince(b.provinceCode); requireProvinceFilter(context,p); if(typeof b.assetType!=='string'||typeof b.sourceId!=='string'||typeof b.name!=='string'||typeof b.latitude!=='number'||typeof b.longitude!=='number')return validation(res,context.requestId,'assetType, sourceId, name, latitude and longitude are required'); return send(res,201,{data:await service.upsertGeoAsset({assetType:b.assetType,sourceId:b.sourceId,name:b.name,provinceCode:p,latitude:b.latitude,longitude:b.longitude,properties:isRecord(b.properties)?b.properties:{},isPublic:b.isPublic===true,layerCode:typeof b.layerCode==='string'?b.layerCode:undefined}),requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname.startsWith('/api/v1/ntdp/sme/')) { requirePermission(context,'sme:read'); await requireOwnedOperator(pool,context,url.pathname.split('/').pop()!,true); return send(res,200,{data:await service.getSmeProfile(url.pathname.split('/').pop()!),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/sme/profiles') { requirePermission(context,'sme:write'); const b=await readJson(req); if(typeof b.operatorId!=='string')return validation(res,context.requestId,'operatorId is required'); await requireOwnedOperator(pool,context,b.operatorId); return send(res,201,{data:await service.createSmeProfile({operatorId:b.operatorId,businessSize:typeof b.businessSize==='string'?b.businessSize:undefined,ownershipType:typeof b.ownershipType==='string'?b.ownershipType:undefined,needs:Array.isArray(b.needs)?b.needs:[]}),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/sme/assessments') { requirePermission(context,'sme:write'); const b=await readJson(req); if(typeof b.smeId!=='string')return validation(res,context.requestId,'smeId is required'); if(context.user.roles.includes('operator'))requireAuthority(context); await requireOwnedResource(pool,context,'sme',b.smeId); return send(res,201,{data:await service.assessSme({smeId:b.smeId,assessorId:context.user.id,score:typeof b.score==='number'?b.score:undefined,findings:isRecord(b.findings)?b.findings:{},recommendedActions:Array.isArray(b.recommendedActions)?b.recommendedActions:[],status:b.status==='final'?'final':'draft'}),requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/membership') { requirePermission(context,'membership:read'); await requireOperatorFilter(pool,context,url.searchParams.get('operatorId')||undefined); return send(res,200,{data:await service.listMemberships(url.searchParams.get('operatorId')||undefined),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/membership') { requirePermission(context,'membership:write'); const b=await readJson(req); if(typeof b.operatorId!=='string')return validation(res,context.requestId,'operatorId is required'); await requireOwnedOperator(pool,context,b.operatorId); if(b.renewalOf!==undefined)return validation(res,context.requestId,'Use the renewal endpoint'); if(!context.user.roles.some(r=>r==='platform_admin'||r==='tpa_regulator')){delete b.feeAmount;delete b.expiresAt;} return send(res,201,{data:await service.applyMembership({operatorId:b.operatorId,feeAmount:typeof b.feeAmount==='number'?b.feeAmount:undefined,expiresAt:typeof b.expiresAt==='string'?b.expiresAt:undefined,renewalOf:typeof b.renewalOf==='string'?b.renewalOf:undefined,notes:typeof b.notes==='string'?b.notes:undefined}),requestId:context.requestId}); }
    if (req.method === 'PATCH' && url.pathname.startsWith('/api/v1/ntdp/membership/')) { requirePermission(context,'membership:write'); requireAuthority(context); const id=url.pathname.split('/').pop()!; const b=await readJson(req); const status=b.status; if(status!=='active'&&status!=='suspended'&&status!=='cancelled')return validation(res,context.requestId,'status must be active, suspended or cancelled'); const data=await service.transitionMembership({membershipId:id,status,changedBy:context.user.id,membershipNumber:typeof b.membershipNumber==='string'?b.membershipNumber:undefined,expiresAt:typeof b.expiresAt==='string'?b.expiresAt:undefined,reason:typeof b.reason==='string'?b.reason:undefined}); if(!data)return send(res,404,{error:{code:'NOT_FOUND',message:'Membership not found'},requestId:context.requestId}); return send(res,200,{data,requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/membership/renewals') { requirePermission(context,'membership:write'); const b=await readJson(req); if(typeof b.membershipId!=='string'||typeof b.expiresAt!=='string')return validation(res,context.requestId,'membershipId and expiresAt are required'); await requireOwnedResource(pool,context,'membership',b.membershipId); if(!context.user.roles.some(r=>r==='platform_admin'||r==='tpa_regulator'))delete b.feeAmount; const data=await service.renewMembership({membershipId:b.membershipId,changedBy:context.user.id,expiresAt:b.expiresAt,feeAmount:typeof b.feeAmount==='number'?b.feeAmount:undefined,notes:typeof b.notes==='string'?b.notes:undefined}); if(!data)return send(res,404,{error:{code:'NOT_FOUND',message:'Membership not found'},requestId:context.requestId}); return send(res,201,{data,requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname.startsWith('/api/v1/ntdp/membership/') && url.pathname.endsWith('/events')) { requirePermission(context,'membership:read'); const parts=url.pathname.split('/'); await requireOwnedResource(pool,context,'membership',parts[parts.length-2],true); return send(res,200,{data:await service.membershipEvents(parts[parts.length-2]),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/membership/expire') { requirePermission(context,'membership:write'); requireAuthority(context); return send(res,200,{data:await service.expireMemberships(),requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/distribution') { requirePermission(context,'distribution:read'); requireAuthority(context); return send(res,200,{data:await service.distributionQueue(url.searchParams.get('channel')||undefined),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/distribution') { requirePermission(context,'distribution:write'); requireAuthority(context); const b=await readJson(req); if(typeof b.channelCode!=='string'||(typeof b.contentId!=='string'&&typeof b.destinationId!=='string'))return validation(res,context.requestId,'channelCode and a contentId or destinationId are required'); const data=await service.queueDistribution({channelCode:b.channelCode,contentId:typeof b.contentId==='string'?b.contentId:undefined,destinationId:typeof b.destinationId==='string'?b.destinationId:undefined}); if(!data)return send(res,404,{error:{code:'NOT_FOUND',message:'Active distribution channel not found'},requestId:context.requestId}); return send(res,201,{data,requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/commerce/readiness') { requirePermission(context,'commerce:read'); return send(res,200,{data:await service.commerceReadiness(),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/commerce/transactions') { requirePermission(context,'commerce:write'); const b=await readJson(req); if(typeof b.transactionType!=='string'||typeof b.amount!=='number')return validation(res,context.requestId,'transactionType and amount are required'); requireAuthority(context); const data=await service.createTransaction({transactionType:b.transactionType,amount:b.amount,currency:typeof b.currency==='string'?b.currency:undefined,operatorId:typeof b.operatorId==='string'?b.operatorId:undefined,providerCode:typeof b.providerCode==='string'?b.providerCode:undefined,idempotencyKey:typeof b.idempotencyKey==='string'?b.idempotencyKey:undefined,metadata:isRecord(b.metadata)?b.metadata:{}}); if(!data)return send(res,404,{error:{code:'NOT_FOUND',message:'Payment provider not found'},requestId:context.requestId}); return send(res,201,{data,requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/regulatory/licenses') { requirePermission(context,'operator:read'); return send(res,200,{data:await service.listLicenses(url.searchParams.get('operatorId')||undefined),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/regulatory/licenses') { requirePermission(context,'operator:register'); const b=await readJson(req); if(typeof b.operatorId!=='string')return validation(res,context.requestId,'operatorId is required'); return send(res,201,{data:await service.applyLicense({operatorId:b.operatorId,licenseType:typeof b.licenseType==='string'?b.licenseType:undefined,documents:Array.isArray(b.documents)?b.documents:[],conditions:isRecord(b.conditions)?b.conditions:{}}),requestId:context.requestId}); }
    if (req.method === 'PATCH' && url.pathname.startsWith('/api/v1/ntdp/regulatory/licenses/')) { requirePermission(context,'operator:approve'); const id=url.pathname.split('/').pop()!; const b=await readJson(req); const allowed=['under_review','approved','suspended','expired','revoked']; if(typeof b.status!=='string'||!allowed.includes(b.status))return validation(res,context.requestId,'status must be under_review, approved, suspended, expired or revoked'); const data=await service.reviewLicense({licenseId:id,status:b.status as any,reviewedBy:context.user.id,licenseNumber:typeof b.licenseNumber==='string'?b.licenseNumber:undefined,expiresAt:typeof b.expiresAt==='string'?b.expiresAt:undefined,notes:typeof b.notes==='string'?b.notes:undefined}); if(!data)return send(res,404,{error:{code:'NOT_FOUND',message:'License not found'},requestId:context.requestId}); return send(res,200,{data,requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/regulatory/inspections') { requirePermission(context,'operator:manage_compliance'); const b=await readJson(req); if(typeof b.licenseId!=='string'||typeof b.operatorId!=='string')return validation(res,context.requestId,'licenseId and operatorId are required'); return send(res,201,{data:await service.createInspection({licenseId:b.licenseId,operatorId:b.operatorId,inspectorId:context.user.id,inspectionDate:typeof b.inspectionDate==='string'?b.inspectionDate:undefined,outcome:typeof b.outcome==='string'?b.outcome:undefined,findings:isRecord(b.findings)?b.findings:{},recommendations:Array.isArray(b.recommendations)?b.recommendations:[],nextDueDate:typeof b.nextDueDate==='string'?b.nextDueDate:undefined}),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/regulatory/compliance-actions') { requirePermission(context,'operator:manage_compliance'); const b=await readJson(req); if(typeof b.operatorId!=='string'||typeof b.actionType!=='string')return validation(res,context.requestId,'operatorId and actionType are required'); return send(res,201,{data:await service.createComplianceAction({operatorId:b.operatorId,licenseId:typeof b.licenseId==='string'?b.licenseId:undefined,inspectionId:typeof b.inspectionId==='string'?b.inspectionId:undefined,actionType:b.actionType,dueAt:typeof b.dueAt==='string'?b.dueAt:undefined,notes:typeof b.notes==='string'?b.notes:undefined,createdBy:context.user.id}),requestId:context.requestId}); }
    if (req.method === 'GET' && url.pathname === '/api/v1/ntdp/distribution/partners') { requirePermission(context,'distribution:read'); requireAuthority(context); return send(res,200,{data:await service.listPartners(url.searchParams.get('status')||undefined),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/distribution/partners') { requirePermission(context,'distribution:write'); requireAuthority(context); const b=await readJson(req); if(typeof b.code!=='string'||typeof b.name!=='string')return validation(res,context.requestId,'code and name are required'); return send(res,201,{data:await service.upsertPartner({code:b.code,name:b.name,partnerType:typeof b.partnerType==='string'?b.partnerType:undefined,endpointUrl:typeof b.endpointUrl==='string'?b.endpointUrl:undefined,capabilities:isRecord(b.capabilities)?b.capabilities:{}}),requestId:context.requestId}); }
    if (req.method === 'POST' && url.pathname === '/api/v1/ntdp/distribution/partners/bindings') { requirePermission(context, 'distribution:write'); requireAuthority(context); const b=await readJson(req); if(typeof b.partnerId!=='string'||typeof b.channelCode!=='string')return validation(res,context.requestId,'partnerId and channelCode are required'); const data=await service.bindPartnerChannel({partnerId:b.partnerId,channelCode:b.channelCode}); if(!data)return send(res,404,{error:{code:'NOT_FOUND',message:'Distribution channel not found'},requestId:context.requestId}); return send(res,201,{data,requestId:context.requestId}); }
    return send(res,404,{error:{code:'NOT_FOUND',message:'NTDP enterprise route not found'},requestId:context.requestId});
  } catch(e:any) { const status=e?.code==='UNAUTHORIZED'?401:e?.code==='FORBIDDEN'?403:e?.code==='VALIDATION_ERROR'?400:500; return send(res,status,{error:{code:e?.code||'INTERNAL_ERROR',message:status===500?'Internal server error':e.message},requestId:req.headers['x-request-id']?.toString()||randomUUID()}); }
}
function parseProvince(value:unknown):ProvinceCode|undefined{if(value===undefined||value===null||value==='')return undefined;if(typeof value!=='string'||!['NCD','CENTRAL','GULF','MILNE_BAY','ORO','MOROBE','MADANG','EAST_SEPIK','WEST_SEPIK','MANUS','NEW_IRELAND','EAST_NEW_BRITAIN','WEST_NEW_BRITAIN','BOUGAINVILLE','ENGA','EASTERN_HIGHLANDS','SIMBU','WESTERN_HIGHLANDS','SOUTHERN_HIGHLANDS','JIWAKA','HELA','WESTERN'].includes(value)){const e:any=new Error('Invalid province code');e.code='VALIDATION_ERROR';throw e;}return value as ProvinceCode;}
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value)}
function validation(res:ServerResponse,requestId:string,message:string):boolean{return send(res,400,{error:{code:'VALIDATION_ERROR',message},requestId})}
function send(res:ServerResponse,status:number,body:unknown):boolean{res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.end(JSON.stringify(body));return true}
