import { describe, expect, it } from 'vitest';
import { AiConciergeService } from './ai-concierge-service';
const service=()=>new AiConciergeService({destinations:{list:async(o?:any)=>({items:[{id:'d1',name:'Kokopo',slug:'kokopo',provinceCode:'EAST_NEW_BRITAIN',description:'Volcanic harbour and cultural destination',publicationStatus:'published',contentVersion:2,updatedAt:'2026-09-08T00:00:00.000Z'},{id:'d2',name:'Port Moresby',slug:'port-moresby',provinceCode:'NCD',description:'Capital city',publicationStatus:'published',contentVersion:1,updatedAt:'2026-09-08T00:00:00.000Z'}].filter((x)=>!o?.provinceCode||x.provinceCode===o.provinceCode)})},content:{list:async(o?:any)=>({items:[{id:'c1',type:'experience',title:'Reef diving',slug:'reef',summary:'Diving in clear tropical water',publicationStatus:'published',version:3,updatedAt:'2026-09-08T00:00:00.000Z',provinceCode:'EAST_NEW_BRITAIN'},{id:'c2',type:'experience',title:'Diving',slug:'diving',summary:'Diving near the capital',publicationStatus:'published',version:1,updatedAt:'2026-09-08T00:00:00.000Z',provinceCode:'NCD'}].filter((x)=>!o?.provinceCode||x.provinceCode===o.provinceCode)})},operators:{list:async(o?:any)=>({items:[{id:'o1',legalName:'Public Tours Ltd',tradingName:'Public Tours',provinceCode:'NCD',status:'active',complianceStatus:'compliant',createdAt:'',updatedAt:''},{id:'o2',legalName:'Kokopo Tours Ltd',tradingName:'Kokopo Tours',provinceCode:'EAST_NEW_BRITAIN',status:'active',complianceStatus:'compliant',createdAt:'',updatedAt:''}].filter((x)=>!o?.provinceCode||x.provinceCode===o.provinceCode)})}} as any);
describe('AiConciergeService',()=>{
 it('passes province scope to destination retrieval',async()=>{const s=service();const r=await s.executeTool({toolName:'search_destinations',input:{query:'kokopo'}},'EAST_NEW_BRITAIN');expect(r.sources[0].provenance).toBe('destination:d1:v2');});
 it('matches natural-language destination questions against published records',async()=>{const s=service();const r=await s.executeTool({toolName:'search_destinations',input:{query:'Where can I visit in Kokopo?'}});expect(r.output.map((x:any)=>x.id)).toEqual(['d1']);});
 it('passes province scope to experience retrieval',async()=>{const s=service();const r=await s.executeTool({toolName:'search_experiences',input:{query:'reef'}},'EAST_NEW_BRITAIN');expect(r.sources[0].id).toBe('c1');});
 it('keeps operator output public and province scoped',async()=>{const s=service();const r=await s.executeTool({toolName:'find_operator',input:{query:'kokopo'}},'EAST_NEW_BRITAIN');expect(r.output).toEqual([{id:'o2',tradingName:'Kokopo Tours',provinceCode:'EAST_NEW_BRITAIN'}]);});
 it('refuses private or regulatory requests',async()=>{const r=await service().answer({message:'What is the operator compliance status?'});expect(r.refused).toBe(true);expect(r.refusalReason).toBe('private_or_regulatory_data');});
});
