import { randomUUID } from 'node:crypto';
import type { ProvinceCode } from '../domain/types';
import type { ContentRepository, DestinationRepository, OperatorRepository } from './contracts';
import type { AiAnswer, AiAuditEvent, AiConversationRequest, AiConversationResponse, AiSourceRef, AiToolDefinition, AiToolRequest, AiToolResult } from '../domain/ai';
import type { AiAuditRepository } from '../persistence/repositories';
import { getAiPolicy, getAiSystemPrompt } from './ai-policy';

export interface AiConciergeDeps { destinations:DestinationRepository; content:ContentRepository; operators:OperatorRepository; audit?:AiAuditRepository; generate?: (input:{message:string;toolResults:AiToolResult[];promptVersion:string;systemPrompt:string;model:string;provider:string})=>Promise<AiAnswer>; }
export const AI_TOOLS:readonly AiToolDefinition[]=[{name:'search_destinations',description:'Find published tourism destinations',risk:'low',allowedSourceKinds:['public_destination']},{name:'search_experiences',description:'Find published tourism experiences',risk:'low',allowedSourceKinds:['public_content']},{name:'find_operator',description:'Find published tourism operator profiles',risk:'low',allowedSourceKinds:['public_operator']}];
const refusalText='I can help with published Papua New Guinea tourism information, but I cannot provide private or regulatory information or assist with unsafe requests.';
export class AiConciergeService {
 constructor(private readonly deps:AiConciergeDeps){}
 listTools():readonly AiToolDefinition[]{return AI_TOOLS;}
 private policy(){return getAiPolicy();}
 private async audit(event:AiAuditEvent,requestId?:string){if(this.deps.audit) await this.deps.audit.record({...event,requestId});}
 async executeTool(request:AiToolRequest,provinceCode?:ProvinceCode,sessionId='unknown',requestId?:string):Promise<AiToolResult>{const definition=AI_TOOLS.find(t=>t.name===request.toolName);if(!definition)throw new Error(`AI tool is not allowlisted: ${request.toolName}`);const query=typeof request.input.query==='string'?request.input.query.trim().toLowerCase():'';if(!query)return{toolName:request.toolName,output:[],sources:[]};await this.audit({sessionId,action:'tool_call',toolName:request.toolName,promptVersion:this.policy().promptVersion,modelVersion:this.policy().model,governed:true,metadata:{queryLength:query.length}},requestId);
  if(request.toolName==='search_destinations'){const r=await this.deps.destinations.list({provinceCode,limit:1000});const items=r.items.filter(i=>i.publicationStatus==='published'&&i.name.toLowerCase().includes(query));const sources=items.map(i=>({id:i.id,kind:'public_destination' as const,title:i.name,provenance:`destination:${i.id}:v${i.contentVersion}`,publicationStatus:'published' as const}));return{toolName:request.toolName,output:items,sources};}
  if(request.toolName==='search_experiences'){const r=await this.deps.content.list({publicationStatus:'published',provinceCode,limit:1000});const items=r.items.filter(i=>i.publicationStatus==='published'&&i.type==='experience'&&i.title.toLowerCase().includes(query));const sources=items.map(i=>({id:i.id,kind:'public_content' as const,title:i.title,provenance:`content:${i.id}:v${i.version}`,publicationStatus:'published' as const}));return{toolName:request.toolName,output:items,sources};}
  const r=await this.deps.operators.list({provinceCode,status:'active',limit:1000});const items=r.items.filter(i=>i.status==='active'&&i.complianceStatus==='compliant'&&Boolean(i.tradingName)&&i.legalName.toLowerCase().includes(query));const sources=items.map(i=>({id:i.id,kind:'public_operator' as const,title:i.tradingName!,provenance:`operator-public:${i.id}`,publicationStatus:'published' as const}));return{toolName:request.toolName,output:items.map(({id,tradingName,provinceCode})=>({id,tradingName,provinceCode})),sources}; }
 async answer(request:AiConversationRequest,requestId?:string):Promise<AiConversationResponse>{const policy=this.policy();const sessionId=request.sessionId?.trim()||randomUUID();const message=request.message.trim();await this.audit({sessionId,action:'request',promptVersion:policy.promptVersion,modelVersion:policy.model,governed:true,metadata:{messageLength:message.length,provinceCode:request.provinceCode}},requestId);const refuse=async(reason:AiConversationResponse['refusalReason'])=>{await this.audit({sessionId,action:'refusal',promptVersion:policy.promptVersion,modelVersion:policy.model,governed:true,metadata:{reason}},requestId);return{sessionId,answer:refusalText,sources:[],modelVersion:policy.model,promptVersion:policy.promptVersion,governed:true,refused:true,refusalReason:reason};};if(!message)return refuse('unsupported');const lower=message.toLowerCase();if(/weapon|violence|exploit|malware|self-harm/.test(lower))return refuse('unsafe_request');if(/password|token|secret|license status|compliance|regulatory|suspended|private (data|information|records|details)|internal/.test(lower))return refuse('private_or_regulatory_data');if(!/(png|papua|tour|travel|visit|destination|experience|hotel|operator|attraction|event)/.test(lower))return refuse('outside_tourism_scope');const toolRequests:AiToolRequest[]=[];if(/destination|where|visit|place|attraction/.test(lower))toolRequests.push({toolName:'search_destinations',input:{query:request.provinceCode?request.provinceCode.replace(/_/g,' '):message}});if(/experience|activity|do|adventure/.test(lower))toolRequests.push({toolName:'search_experiences',input:{query:message}});if(/operator|tour company|tour operator/.test(lower))toolRequests.push({toolName:'find_operator',input:{query:message}});const toolResults=await Promise.all(toolRequests.map(t=>this.executeTool(t,request.provinceCode,sessionId,requestId)));const sources:AiSourceRef[]=toolResults.flatMap(r=>r.sources);let response:AiConversationResponse;if(this.deps.generate){const generated=await this.deps.generate({message,toolResults,promptVersion:policy.promptVersion,systemPrompt:getAiSystemPrompt(policy.promptVersion),model:policy.model,provider:policy.provider});response={...generated,sessionId,modelVersion:generated.modelVersion||policy.model,promptVersion:policy.promptVersion,governed:true,sources:generated.sources.length?generated.sources:sources};}else{response={sessionId,answer:sources.length?`I found ${sources.length} published tourism source${sources.length===1?'':'s'} relevant to your request.`:'I can help with published Papua New Guinea tourism information. Please provide a destination, experience, event, or operator you are interested in.',sources,modelVersion:policy.model,promptVersion:policy.promptVersion,governed:true};}await this.audit({sessionId,action:'response',promptVersion:policy.promptVersion,modelVersion:response.modelVersion,governed:true,metadata:{sourceCount:response.sources.length}},requestId);return response; }
}
