import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import type { ProvinceCode } from '../domain/types';

export class NtdpCoreService {
  constructor(private readonly pool: Pool) {}
  async snapshotOperators(snapshotDate = new Date().toISOString().slice(0, 10)) {
    await this.pool.query(`insert into analytics.operator_snapshot(snapshot_date,operator_id,province_code,status,compliance_status) select $1::date,id,province_code,status::text,compliance_status::text from operators on conflict (snapshot_date,operator_id) do update set province_code=excluded.province_code,status=excluded.status,compliance_status=excluded.compliance_status`, [snapshotDate]);
    const r = await this.pool.query(`select snapshot_date,count(*)::int operators,count(*) filter (where status='active')::int active_operators,count(*) filter (where compliance_status='compliant')::int compliant_operators from analytics.operator_snapshot where snapshot_date=$1 group by snapshot_date`, [snapshotDate]);
    return r.rows[0] ?? { snapshot_date: snapshotDate, operators: 0, active_operators: 0, compliant_operators: 0 };
  }
  async recordVisitorEvent(input:{eventType:string;source:string;provinceCode?:ProvinceCode;operatorId?:string;destinationId?:string;metadata?:Record<string,unknown>}) {
    const r=await this.pool.query(`insert into analytics.visitor_event_fact(event_id,occurred_at,source,province_code,operator_id,destination_id,event_type,metadata) values($1,now(),$2,$3,$4,$5,$6,$7) returning *`,[randomUUID(),input.source,input.provinceCode??null,input.operatorId??null,input.destinationId??null,input.eventType,JSON.stringify(input.metadata??{})]);
    return r.rows[0];
  }
  async geoAssets(provinceCode?:ProvinceCode){const r=await this.pool.query(`select id,asset_type,source_id,name,province_code,latitude,longitude,properties,is_public,updated_at from gis.tourism_geo_asset ${provinceCode?'where province_code=$1':''} order by name`,provinceCode?[provinceCode]:[]);return r.rows;}
  async upsertGeoAsset(input:{assetType:string;sourceId:string;name:string;provinceCode?:ProvinceCode;latitude:number;longitude:number;properties?:Record<string,unknown>;isPublic?:boolean}){const r=await this.pool.query(`insert into gis.tourism_geo_asset(asset_type,source_id,name,province_code,latitude,longitude,properties,is_public) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict (asset_type,source_id) do update set name=excluded.name,province_code=excluded.province_code,latitude=excluded.latitude,longitude=excluded.longitude,properties=excluded.properties,is_public=excluded.is_public,updated_at=now() returning id,asset_type,source_id,name,province_code,latitude,longitude,properties,is_public,updated_at`,[input.assetType,input.sourceId,input.name,input.provinceCode??null,input.latitude,input.longitude,JSON.stringify(input.properties??{}),input.isPublic??false]);return r.rows[0];}
  async getSmeProfile(operatorId:string){const r=await this.pool.query(`select * from sme_profiles where operator_id=$1`,[operatorId]);return r.rows[0]??null;}
  async createSmeProfile(input:{operatorId:string;businessSize?:string;ownershipType?:string;needs?:unknown[]}){const r=await this.pool.query(`insert into sme_profiles(operator_id,business_size,ownership_type,needs) values($1,$2,$3,$4) on conflict (operator_id) do update set business_size=excluded.business_size,ownership_type=excluded.ownership_type,needs=excluded.needs,updated_at=now() returning *`,[input.operatorId,input.businessSize??'unknown',input.ownershipType??null,JSON.stringify(input.needs??[])]);return r.rows[0];}
  async assessSme(input:{smeId:string;assessorId?:string;score?:number;findings?:Record<string,unknown>;recommendedActions?:unknown[];status?:string}){const r=await this.pool.query(`insert into sme_assessments(sme_id,assessor_id,score,findings,recommended_actions,status) values($1,$2,$3,$4,$5,$6) returning *`,[input.smeId,input.assessorId??null,input.score??null,JSON.stringify(input.findings??{}),JSON.stringify(input.recommendedActions??[]),input.status??'draft']);await this.pool.query(`update sme_profiles set development_status='assessed',updated_at=now() where id=$1`,[input.smeId]);return r.rows[0];}
  async applyMembership(input:{operatorId:string;feeAmount?:number;expiresAt?:string;renewalOf?:string;notes?:string}){const r=await this.pool.query(`insert into tia_memberships(operator_id,status,fee_amount,expires_at,renewal_of,notes) values($1,'applied',$2,$3,$4,$5) returning *`,[input.operatorId,input.feeAmount??null,input.expiresAt??null,input.renewalOf??null,input.notes??null]);return r.rows[0];}
  async listMemberships(operatorId?:string){const r=await this.pool.query(`select * from tia_memberships ${operatorId?'where operator_id=$1':''} order by created_at desc`,operatorId?[operatorId]:[]);return r.rows;}
  async transitionMembership(input:{membershipId:string;status:'active'|'suspended'|'cancelled';changedBy:string;reason?:string;membershipNumber?:string;expiresAt?:string}){const r=await this.pool.query(`update tia_memberships set status=$2,membership_number=coalesce($3,membership_number),approved_at=case when $2='active' then coalesce(approved_at,now()) else approved_at end,expires_at=coalesce($4::date,expires_at),updated_at=now() where id=$1 and status <> 'cancelled' returning *`,[input.membershipId,input.status,input.membershipNumber??null,input.expiresAt??null]);if(!r.rows[0])return null;await this.pool.query(`insert into tia_membership_events(membership_id,from_status,to_status,changed_by,reason) values($1,$2,$3,$4,$5)`,[r.rows[0].id,null,r.rows[0].status,input.changedBy,input.reason??'membership lifecycle transition']);return r.rows[0];}
  async renewMembership(input:{membershipId:string;changedBy:string;expiresAt:string;feeAmount?:number;notes?:string}){const r=await this.pool.query(`insert into tia_memberships(operator_id,status,fee_amount,expires_at,renewal_of,notes) select operator_id,'applied',$2,$3,id,$4 from tia_memberships where id=$1 returning *`,[input.membershipId,input.feeAmount??null,input.expiresAt,input.notes??null]);if(!r.rows[0])return null;await this.pool.query(`insert into tia_membership_events(membership_id,to_status,changed_by,reason) values($1,'applied',$2,'renewal application')`,[r.rows[0].id,input.changedBy]);return r.rows[0];}
  async membershipEvents(membershipId:string){const r=await this.pool.query(`select * from tia_membership_events where membership_id=$1 order by changed_at desc`,[membershipId]);return r.rows;}
  async expireMemberships(){const r=await this.pool.query(`select tia_expire_memberships()::int expired`);return r.rows[0];}
  async distributionQueue(channelCode?:string){const r=await this.pool.query(`select p.*,c.code channel_code,c.name channel_name from distribution.publications p join distribution.channels c on c.id=p.channel_id ${channelCode?'where c.code=$1':''} order by p.created_at desc`,channelCode?[channelCode]:[]);return r.rows;}
  async queueDistribution(input:{channelCode:string;contentId?:string;destinationId?:string}){const r=await this.pool.query(`insert into distribution.publications(channel_id,content_id,destination_id) select id,$2::uuid,$3::uuid from distribution.channels where code=$1 and status='active' returning *`,[input.channelCode,input.contentId??null,input.destinationId??null]);return r.rows[0]??null;}
  async createTransaction(input:{transactionType:string;amount:number;currency?:string;operatorId?:string;providerCode?:string;idempotencyKey?:string;metadata?:Record<string,unknown>}){const r=await this.pool.query(`insert into commerce.transactions(provider_id,operator_id,transaction_type,amount,currency,idempotency_key,metadata) select p.id,$2,$3,$4,$5,$6,$7 from commerce.payment_providers p where p.code=$1 returning *`,[input.providerCode??'platform-ready',input.operatorId??null,input.transactionType,input.amount,input.currency??'PGK',input.idempotencyKey??null,JSON.stringify(input.metadata??{})]);return r.rows[0]??null;}
  async commerceReadiness(){const providers=await this.pool.query(`select code,name,status,capabilities from commerce.payment_providers order by name`);return{providers:providers.rows,transactionModel:'commerce.transactions',credentialStorage:'external-secret-manager'};}
  async listLicenses(operatorId?:string){const r=await this.pool.query(`select * from regulatory_licenses ${operatorId?'where operator_id=$1':''} order by created_at desc`,operatorId?[operatorId]:[]);return r.rows;}
  async applyLicense(input:{operatorId:string;licenseType?:string;documents?:unknown[];conditions?:Record<string,unknown>}){const r=await this.pool.query(`insert into regulatory_licenses(operator_id,license_type,documents,conditions) values($1,$2,$3,$4) returning *`,[input.operatorId,input.licenseType??'tourism_operator',JSON.stringify(input.documents??[]),JSON.stringify(input.conditions??{})]);return r.rows[0];}
  async reviewLicense(input:{licenseId:string;status:'under_review'|'approved'|'suspended'|'expired'|'revoked';reviewedBy:string;licenseNumber?:string;expiresAt?:string;notes?:string}){const r=await this.pool.query(`update regulatory_licenses set status=$2,license_number=coalesce($3,license_number),approved_at=case when $2='approved' then now() else approved_at end,expires_at=coalesce($4::timestamptz,expires_at),reviewed_by=$5,review_notes=coalesce($6,review_notes),updated_at=now() where id=$1 returning *`,[input.licenseId,input.status,input.licenseNumber??null,input.expiresAt??null,input.reviewedBy,input.notes??null]);return r.rows[0]??null;}
  async createInspection(input:{licenseId:string;operatorId:string;inspectorId:string;inspectionDate?:string;outcome?:string;findings?:Record<string,unknown>;recommendations?:unknown[];nextDueDate?:string}){const r=await this.pool.query(`insert into regulatory_inspections(license_id,operator_id,inspector_id,inspection_date,outcome,findings,recommendations,next_due_date) values($1,$2,$3,coalesce($4::date,current_date),$5,$6,$7,$8::date) returning *`,[input.licenseId,input.operatorId,input.inspectorId,input.inspectionDate??null,input.outcome??'pending',JSON.stringify(input.findings??{}),JSON.stringify(input.recommendations??[]),input.nextDueDate??null]);return r.rows[0];}
  async createComplianceAction(input:{operatorId:string;licenseId?:string;inspectionId?:string;actionType:string;dueAt?:string;notes?:string;createdBy:string}){const r=await this.pool.query(`insert into regulatory_compliance_actions(operator_id,license_id,inspection_id,action_type,due_at,notes,created_by) values($1,$2,$3,$4,$5,$6,$7) returning *`,[input.operatorId,input.licenseId??null,input.inspectionId??null,input.actionType,input.dueAt??null,input.notes??null,input.createdBy]);return r.rows[0];}
  async listPartners(status?:string){const r=await this.pool.query(`select p.*,coalesce(json_agg(json_build_object('channelCode',c.code,'channelName',c.name,'status',b.status)) filter (where c.id is not null),'[]'::json) channels from distribution.partners p left join distribution.partner_channel_bindings b on b.partner_id=p.id left join distribution.channels c on c.id=b.channel_id ${status?'where p.status=$1':''} group by p.id order by p.created_at desc`,status?[status]:[]);return r.rows;}
  async upsertPartner(input:{code:string;name:string;partnerType?:string;endpointUrl?:string;capabilities?:Record<string,unknown>}){const r=await this.pool.query(`insert into distribution.partners(code,name,partner_type,endpoint_url,capabilities) values($1,$2,$3,$4,$5) on conflict(code) do update set name=excluded.name,partner_type=excluded.partner_type,endpoint_url=excluded.endpoint_url,capabilities=excluded.capabilities,updated_at=now() returning *`,[input.code,input.name,input.partnerType??'third_party',input.endpointUrl??null,JSON.stringify(input.capabilities??{})]);return r.rows[0];}
  async bindPartnerChannel(input:{partnerId:string;channelCode:string}){const r=await this.pool.query(`insert into distribution.partner_channel_bindings(partner_id,channel_id) select $1,id from distribution.channels where code=$2 on conflict(partner_id,channel_id) do update set status='active' returning *`,[input.partnerId,input.channelCode]);return r.rows[0]??null;}
}
