import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import type { ProvinceCode } from '../domain/types';

export class NtdpCoreService {
  constructor(private readonly pool: Pool) {}
  async snapshotOperators(snapshotDate = new Date().toISOString().slice(0, 10)) {
    await this.pool.query(`insert into analytics.operator_snapshot(snapshot_date,operator_id,province_code,status,compliance_status) select $1::date,id,province_code,status::text,compliance_status::text from operators on conflict (snapshot_date,operator_id) do update set province_code=excluded.province_code,status=excluded.status,compliance_status=excluded.compliance_status`, [snapshotDate]);
    const r = await this.pool.query(`select snapshot_date,count(*)::int operators,count(*) filter (where status='active')::int active_operators,count(*) filter (where compliance_status='compliant')::int compliant_operators from analytics.operator_snapshot where snapshot_date=$1 group by snapshot_date`, [snapshotDate]);
    return r.rows[0] ?? { snapshot_date: snapshotDate, operators: 0, active_operators: 0, compliant_operators: 0 };
  }
  async recordVisitorEvent(input:{eventType:string;source:string;provinceCode?:ProvinceCode;operatorId?:string;destinationId?:string;metadata?:Record<string,unknown>}) {
    const r=await this.pool.query(`insert into analytics.visitor_event_fact(event_id,occurred_at,source,province_code,operator_id,destination_id,event_type,metadata) values($1,now(),$2,$3,$4,$5,$6,$7) returning *`,[randomUUID(),input.source,input.provinceCode??null,input.operatorId??null,input.destinationId??null,input.eventType,JSON.stringify(input.metadata??{})]);
    return r.rows[0];
  }
  async geoAssets(provinceCode?:ProvinceCode){const r=await this.pool.query(`select id,asset_type,source_id,name,province_code,latitude,longitude,properties,is_public,updated_at from gis.tourism_geo_asset ${provinceCode?'where province_code=$1':''} order by name`,provinceCode?[provinceCode]:[]);return r.rows;}
  async upsertGeoAsset(input:{assetType:string;sourceId:string;name:string;provinceCode?:ProvinceCode;latitude:number;longitude:number;properties?:Record<string,unknown>;isPublic?:boolean}){const r=await this.pool.query(`insert into gis.tourism_geo_asset(asset_type,source_id,name,province_code,latitude,longitude,properties,is_public) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict (asset_type,source_id) do update set name=excluded.name,province_code=excluded.province_code,latitude=excluded.latitude,longitude=excluded.longitude,properties=excluded.properties,is_public=excluded.is_public,updated_at=now() returning id,asset_type,source_id,name,province_code,latitude,longitude,properties,is_public,updated_at`,[input.assetType,input.sourceId,input.name,input.provinceCode??null,input.latitude,input.longitude,JSON.stringify(input.properties??{}),input.isPublic??false]);return r.rows[0];}
  async getSmeProfile(operatorId:string){const r=await this.pool.query(`select * from sme_profiles where operator_id=$1`,[operatorId]);return r.rows[0]??null;}
  async createSmeProfile(input:{operatorId:string;businessSize?:string;ownershipType?:string;needs?:unknown[]}){const r=await this.pool.query(`insert into sme_profiles(operator_id,business_size,ownership_type,needs) values($1,$2,$3,$4) on conflict (operator_id) do update set business_size=excluded.business_size,ownership_type=excluded.ownership_type,needs=excluded.needs,updated_at=now() returning *`,[input.operatorId,input.businessSize??'unknown',input.ownershipType??null,JSON.stringify(input.needs??[])]);return r.rows[0];}
  async assessSme(input:{smeId:string;assessorId?:string;score?:number;findings?:Record<string,unknown>;recommendedActions?:unknown[];status?:string}){const r=await this.pool.query(`insert into sme_assessments(sme_id,assessor_id,score,findings,recommended_actions,status) values($1,$2,$3,$4,$5,$6) returning *`,[input.smeId,input.assessorId??null,input.score??null,JSON.stringify(input.findings??{}),JSON.stringify(input.recommendedActions??[]),input.status??'draft']);await this.pool.query(`update sme_profiles set development_status='assessed',updated_at=now() where id=$1`,[input.smeId]);return r.rows[0];}
  async applyMembership(input:{operatorId:string;feeAmount?:number;expiresAt?:string;renewalOf?:string;notes?:string}){const r=await this.pool.query(`insert into tia_memberships(operator_id,status,fee_amount,expires_at,renewal_of,notes) values($1,'applied',$2,$3,$4,$5) returning *`,[input.operatorId,input.feeAmount??null,input.expiresAt??null,input.renewalOf??null,input.notes??null]);return r.rows[0];}
  async listMemberships(operatorId?:string){const r=await this.pool.query(`select * from tia_memberships ${operatorId?'where operator_id=$1':''} order by created_at desc`,operatorId?[operatorId]:[]);return r.rows;}
  async distributionQueue(channelCode?:string){const r=await this.pool.query(`select p.*,c.code channel_code,c.name channel_name from distribution.publications p join distribution.channels c on c.id=p.channel_id ${channelCode?'where c.code=$1':''} order by p.created_at desc`,channelCode?[channelCode]:[]);return r.rows;}
  async queueDistribution(input:{channelCode:string;contentId?:string;destinationId?:string}){const r=await this.pool.query(`insert into distribution.publications(channel_id,content_id,destination_id) select id,$2::uuid,$3::uuid from distribution.channels where code=$1 and status='active' returning *`,[input.channelCode,input.contentId??null,input.destinationId??null]);return r.rows[0]??null;}
  async createTransaction(input:{transactionType:string;amount:number;currency?:string;operatorId?:string;providerCode?:string;idempotencyKey?:string;metadata?:Record<string,unknown>}){const r=await this.pool.query(`insert into commerce.transactions(provider_id,operator_id,transaction_type,amount,currency,idempotency_key,metadata) select p.id,$2,$3,$4,$5,$6,$7 from commerce.payment_providers p where p.code=$1 returning *`,[input.providerCode??'platform-ready',input.operatorId??null,input.transactionType,input.amount,input.currency??'PGK',input.idempotencyKey??null,JSON.stringify(input.metadata??{})]);return r.rows[0]??null;}
  async commerceReadiness(){const providers=await this.pool.query(`select code,name,status,capabilities from commerce.payment_providers order by name`);return{providers:providers.rows,transactionModel:'commerce.transactions',credentialStorage:'external-secret-manager'};}
}
