import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import type { ProvinceCode } from '../domain/types';

export class NtdpCoreService {
  constructor(private readonly pool: Pool) {}
  async snapshotOperators(snapshotDate = new Date().toISOString().slice(0, 10)) { await this.pool.query(`insert into analytics.operator_snapshot(snapshot_date,operator_id,province_code,status,compliance_status) select $1::date,id,province_code,status::text,compliance_status::text from operators on conflict (snapshot_date,operator_id) do update set province_code=excluded.province_code,status=excluded.status,compliance_status=excluded.compliance_status`, [snapshotDate]); const r = await this.pool.query(`select snapshot_date,count(*)::int operators,count(*) filter (where status='active')::int active_operators,count(*) filter (where compliance_status='compliant')::int compliant_operators from analytics.operator_snapshot where snapshot_date=$1 group by snapshot_date`, [snapshotDate]); return r.rows[0] ?? { snapshot_date: snapshotDate, operators: 0, active_operators: 0, compliant_operators: 0 }; }
  async refreshDailyMetrics(runDate = new Date().toISOString().slice(0, 10)) { const started = await this.pool.query(`insert into analytics.etl_runs(job_name,run_date,status) values('daily-tourism-metrics',$1,'running') returning id`, [runDate]); try { const r = await this.pool.query(`select analytics.refresh_daily_metrics($1::date)::int affected`, [runDate]); await this.pool.query(`update analytics.etl_runs set status='succeeded',finished_at=now(),rows_affected=$2 where id=$1`, [started.rows[0].id, r.rows[0]?.affected ?? 0]); return { runId: started.rows[0].id, runDate, status: 'succeeded', rowsAffected: r.rows[0]?.affected ?? 0 }; } catch (error) { await this.pool.query(`update analytics.etl_runs set status='failed',finished_at=now(),error_message=$2 where id=$1`, [started.rows[0].id, error instanceof Error ? error.message : 'warehouse metric refresh failed']); throw error; } }
  async dailyMetrics(metricCode?: string, provinceCode?: ProvinceCode, fromDate?: string, toDate?: string) { const clauses: string[] = []; const params: unknown[] = []; if (metricCode) { params.push(metricCode); clauses.push(`metric_code=$${params.length}`); } if (provinceCode) { params.push(provinceCode); clauses.push(`province_code=$${params.length}`); } if (fromDate) { params.push(fromDate); clauses.push(`metric_date >= $${params.length}::date`); } if (toDate) { params.push(toDate); clauses.push(`metric_date <= $${params.length}::date`); } const r = await this.pool.query(`select metric_date,metric_code,province_code,metric_value,source,created_at from analytics.daily_metric_fact ${clauses.length ? 'where ' + clauses.join(' and ') : ''} order by metric_date desc,metric_code,province_code`, params); return r.rows; }
  async warehouseEtlRuns(limit = 50) { const safeLimit = Math.min(Math.max(limit, 1), 200); const r = await this.pool.query(`select id,job_name,run_date,started_at,finished_at,status,rows_affected,error_message from analytics.etl_runs order by started_at desc limit $1`, [safeLimit]); return r.rows; }
  async recordVisitorEvent(input: { eventType: string; source: string; provinceCode?: ProvinceCode; operatorId?: string; destinationId?: string; metadata?: Record<string, unknown> }) { const r = await this.pool.query(`insert into analytics.visitor_event_fact(event_id,occurred_at,source,province_code,operator_id,destination_id,event_type,metadata) values($1,now(),$2,$3,$4,$5,$6,$7) returning *`, [randomUUID(), input.source, input.provinceCode ?? null, input.operatorId ?? null, input.destinationId ?? null, input.eventType, JSON.stringify(input.metadata ?? {})]); return r.rows[0]; }
  async geoAssets(provinceCode?: ProvinceCode, layerCode?: string, publicOnly = false) { const clauses: string[] = []; const params: unknown[] = []; if (provinceCode) { params.push(provinceCode); clauses.push(`province_code=$${params.length}`); } if (layerCode) { params.push(layerCode); clauses.push(`layer_code=$${params.length}`); } if (publicOnly) clauses.push(`is_public=true and visibility_scope='public'`); const r = await this.pool.query(`select id,asset_type,source_id,name,province_code,latitude,longitude,properties,is_public,layer_code,visibility_scope,updated_at from gis.tourism_geo_asset ${clauses.length ? 'where ' + clauses.join(' and ') : ''} order by name`, params); return r.rows; }
  async geoJsonAssets(provinceCode?: ProvinceCode, layerCode?: string) { const clauses = [`is_public=true`,`visibility_scope='public'`]; const params: unknown[] = []; if (provinceCode) { params.push(provinceCode); clauses.push(`province_code=$${params.length}`); } if (layerCode) { params.push(layerCode); clauses.push(`layer_code=$${params.length}`); } const r = await this.pool.query(`select jsonb_build_object('type','Feature','id',id,'geometry',st_asgeojson(location)::jsonb,'properties',jsonb_build_object('id',id,'assetType',asset_type,'layerCode',layer_code,'name',name,'provinceCode',province_code,'properties',properties)) as feature from gis.tourism_geo_asset where ${clauses.join(' and ')} order by name`, params); return { type: 'FeatureCollection', features: r.rows.map(row => row.feature) }; }
  async syncRegistryGeoAssets() { const r = await this.pool.query(`select gis.sync_registry_geo_assets()::int affected`); return { affected: r.rows[0]?.affected ?? 0 }; }
  async geoLayers() { const r = await this.pool.query(`select layer_code,name,description,source_domain,geometry_type,authoritative,public_default,updated_at from gis.layer_definitions order by layer_code`); return r.rows; }
  async upsertGeoAsset(input: { assetType: string; sourceId: string; name: string; provinceCode?: ProvinceCode; latitude: number; longitude: number; properties?: Record<string, unknown>; isPublic?: boolean; layerCode?: string }) { const r = await this.pool.query(`insert into gis.tourism_geo_asset(asset_type,source_id,name,province_code,latitude,longitude,properties,is_public,layer_code,visibility_scope) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) on conflict(asset_type,source_id) do update set name=excluded.name,province_code=excluded.province_code,latitude=excluded.latitude,longitude=excluded.longitude,properties=excluded.properties,is_public=excluded.is_public,layer_code=excluded.layer_code,visibility_scope=excluded.visibility_scope,updated_at=now() returning id,asset_type,source_id,name,province_code,latitude,longitude,properties,is_public,layer_code,visibility_scope,updated_at`, [input.assetType,input.sourceId,input.name,input.provinceCode ?? null,input.latitude,input.longitude,JSON.stringify(input.properties ?? {}),input.isPublic ?? false,input.layerCode ?? input.assetType,input.isPublic ? 'public' : 'internal']); return r.rows[0]; }
  async getSmeProfile(operatorId: string) { const r = await this.pool.query(`select * from sme_profiles where operator_id=$1`, [operatorId]); return r.rows[0] ?? null; }
  async createSmeProfile(input: { operatorId: string; businessSize?: string; ownershipType?: string; needs?: unknown[] }) { const r = await this.pool.query(`insert into sme_profiles(operator_id,business_size,ownership_type,needs) values($1,$2,$3,$4) on conflict(operator_id) do update set business_size=excluded.business_size,ownership_type=excluded.ownership_type,needs=excluded.needs,updated_at=now() returning *`, [input.operatorId,input.businessSize ?? 'unknown',input.ownershipType ?? null,JSON.stringify(input.needs ?? [])]); return r.rows[0]; }
  async assessSme(input: { smeId: string; assessorId?: string; score?: number; findings?: Record<string, unknown>; recommendedActions?: unknown[]; status?: string }) { const r=await this.pool.query(`insert into sme_assessments(sme_id,assessor_id,score,findings,recommended_actions,status) values($1,$2,$3,$4,$5,$6) returning *`,[input.smeId,input.assessorId??null,input.score??null,JSON.stringify(input.findings??{}),JSON.stringify(input.recommendedActions??[]),input.status??'draft']); await this.pool.query(`update sme_profiles set development_status='assessed',updated_at=now() where id=$1`,[input.smeId]); return r.rows[0]; }
  async applyMembership(input: { operatorId: string; feeAmount?: number; expiresAt?: string; renewalOf?: string; notes?: string }) { const r=await this.pool.query(`insert into tia_memberships(operator_id,status,fee_amount,expires_at,renewal_of,notes) values($1,'applied',$2,$3,$4,$5) returning *`,[input.operatorId,input.feeAmount??null,input.expiresAt??null,input.renewalOf??null,input.notes??null]); return r.rows[0]; }
  async listMemberships(operatorId?: string) { const r=await this.pool.query(`select * from tia_memberships ${operatorId?'where operator_id=$1':''} order by created_at desc`,operatorId?[operatorId]:[]); return r.rows; }
  async transitionMembership(input: { membershipId:string; status:'active'|'suspended'|'cancelled'; changedBy:string; reason?:string; membershipNumber?:string; expiresAt?:string }) { const r=await this.pool.query(`update tia_memberships set status=$2,membership_number=coalesce($3,membership_number),approved_at=case when $2='active' then coalesce(approved_at,now()) else approved_at end,expires_at=coalesce($4::date,expires_at),updated_at=now() where id=$1 and status <> 'cancelled' returning *`,[input.membershipId,input.status,input.membershipNumber??null,input.expiresAt??null]); return r.rows[0]??null; }
  async renewMembership(input:{membershipId:string;changedBy:string;expiresAt:string;feeAmount?:number;notes?:string}) { const r=await this.pool.query(`insert into tia_memberships(operator_id,status,fee_amount,expires_at,renewal_of,notes) select operator_id,'applied',$2,$3,id,$4 from tia_memberships where id=$1 returning *`,[input.membershipId,input.feeAmount??null,input.expiresAt,input.notes??null]); return r.rows[0]??null; }
  async membershipEvents(membershipId:string){const r=await this.pool.query(`select * from tia_membership_events where membership_id=$1 order by changed_at desc`,[membershipId]);return r.rows;}
  async expireMemberships(){const r=await this.pool.query(`select tia_expire_memberships()::int expired`);return r.rows[0]??{expired:0};}
  async distributionQueue(channelCode?:string){const r=await this.pool.query(`select p.*,c.code channel_code,c.name channel_name from distribution.publications p join distribution.channels c on c.id=p.channel_id ${channelCode?'where c.code=$1':''} order by p.created_at desc`,channelCode?[channelCode]:[]);return r.rows;}
  async queueDistribution(input:{channelCode:string;contentId?:string;destinationId?:string}){const r=await this.pool.query(`insert into distribution.publications(channel_id,content_id,destination_id) select id,$2::uuid,$3::uuid from distribution.channels where code=$1 and status='active' returning *`,[input.channelCode,input.contentId??null,input.destinationId??null]);return r.rows[0]??null;}
  async createTransaction(input:{transactionType:string;amount:number;currency?:string;operatorId?:string;providerCode?:string;idempotencyKey?:string;metadata?:Record<string,unknown>}){const r=await this.pool.query(`insert into commerce.transactions(provider_id,operator_id,transaction_type,amount,currency,idempotency_key,metadata) select p.id,$2,$3,$4,$5,$6,$7 from commerce.payment_providers p where p.code=$1 returning *`,[input.providerCode??'platform-ready',input.operatorId??null,input.transactionType,input.amount,input.currency??'PGK',input.idempotencyKey??null,JSON.stringify(input.metadata??{})]);return r.rows[0]??null;}
  async commerceReadiness(){const providers=await this.pool.query(`select code,name,status,capabilities from commerce.payment_providers order by name`);return {providers:providers.rows,transactionModel:'commerce.transactions',credentialStorage:'external-secret-manager'};}
  async listLicenses(operatorId?:string){const r=await this.pool.query(`select * from regulatory_licenses ${operatorId?'where operator_id=$1':''} order by created_at desc`,operatorId?[operatorId]:[]);return r.rows;}
  async applyLicense(input:{operatorId:string;licenseType?:string;documents?:unknown[];conditions?:Record<string,unknown>}){const r=await this.pool.query(`insert into regulatory_licenses(operator_id,license_type,documents,conditions) values($1,$2,$3,$4) returning *`,[input.operatorId,input.licenseType??'tourism_operator',JSON.stringify(input.documents??[]),JSON.stringify(input.conditions??{})]);return r.rows[0];}
  async reviewLicense(input:{licenseId:string;status:'under_review'|'approved'|'suspended'|'expired'|'revoked';reviewedBy:string;licenseNumber?:string;expiresAt?:string;notes?:string;reason?:string}){const current=await this.pool.query(`select status from regulatory_licenses where id=$1`,[input.licenseId]); if(!current.rows[0])return null; const r=await this.pool.query(`update regulatory_licenses set status=$2,license_number=coalesce($3,license_number),approved_at=case when $2='approved' then coalesce(approved_at,now()) else approved_at end,expires_at=coalesce($4::timestamptz,expires_at),reviewed_by=$5,review_notes=coalesce($6,review_notes),updated_at=now() where id=$1 returning *`,[input.licenseId,input.status,input.licenseNumber??null,input.expiresAt??null,input.reviewedBy,input.notes??null]); if(r.rows[0]&&current.rows[0].status!==input.status)await this.pool.query(`insert into regulatory_status_events(entity_type,entity_id,from_status,to_status,changed_by,reason,metadata) values('license',$1,$2,$3,$4,$5,$6)`,[input.licenseId,current.rows[0].status,input.status,input.reviewedBy,input.reason??input.notes??null,JSON.stringify({licenseNumber:input.licenseNumber??null})]); await this.pool.query(`select regulatory_sync_operator_compliance()`); return r.rows[0]??null;}
  async createInspection(input:{licenseId:string;operatorId:string;inspectorId:string;inspectionDate?:string;outcome?:string;findings?:Record<string,unknown>;recommendations?:unknown[];nextDueDate?:string}){const outcome=input.outcome??'pending'; if(!['pending','passed','conditional','failed'].includes(outcome))throw Object.assign(new Error('Invalid inspection outcome'),{code:'VALIDATION_ERROR'}); const r=await this.pool.query(`insert into regulatory_inspections(license_id,operator_id,inspector_id,inspection_date,outcome,findings,recommendations,next_due_date) values($1,$2,$3,coalesce($4::date,current_date),$5,$6,$7,$8::date) returning *`,[input.licenseId,input.operatorId,input.inspectorId,input.inspectionDate??null,outcome,JSON.stringify(input.findings??{}),JSON.stringify(input.recommendations??[]),input.nextDueDate??null]); if(r.rows[0])await this.pool.query(`insert into regulatory_status_events(entity_type,entity_id,to_status,changed_by,metadata) values('inspection',$1,$2,$3,$4)`,[r.rows[0].id,outcome,input.inspectorId,JSON.stringify({licenseId:input.licenseId})]); return r.rows[0];}
  async listInspections(operatorId?:string,licenseId?:string){const clauses:string[]=[];const params:unknown[]=[];if(operatorId){params.push(operatorId);clauses.push(`operator_id=$${params.length}`);}if(licenseId){params.push(licenseId);clauses.push(`license_id=$${params.length}`);}const r=await this.pool.query(`select * from regulatory_inspections ${clauses.length?'where '+clauses.join(' and '):''} order by inspection_date desc,created_at desc`,params);return r.rows;}
  async updateInspection(input:{inspectionId:string;inspectorId:string;outcome?:'pending'|'passed'|'conditional'|'failed';findings?:Record<string,unknown>;recommendations?:unknown[];nextDueDate?:string;reason?:string}){const current=await this.pool.query(`select outcome from regulatory_inspections where id=$1`,[input.inspectionId]);if(!current.rows[0])return null;const r=await this.pool.query(`update regulatory_inspections set outcome=coalesce($2,outcome),findings=coalesce($3,findings),recommendations=coalesce($4,recommendations),next_due_date=coalesce($5::date,next_due_date),updated_at=now() where id=$1 returning *`,[input.inspectionId,input.outcome??null,input.findings?JSON.stringify(input.findings):null,input.recommendations?JSON.stringify(input.recommendations):null,input.nextDueDate??null]);if(r.rows[0]&&input.outcome&&current.rows[0].outcome!==input.outcome)await this.pool.query(`insert into regulatory_status_events(entity_type,entity_id,from_status,to_status,changed_by,reason) values('inspection',$1,$2,$3,$4,$5)`,[input.inspectionId,current.rows[0].outcome,input.outcome,input.inspectorId,input.reason??null]);return r.rows[0]??null;}
  async createComplianceAction(input:{operatorId:string;licenseId?:string;inspectionId?:string;actionType:string;dueAt?:string;notes?:string;createdBy:string}){const r=await this.pool.query(`insert into regulatory_compliance_actions(operator_id,license_id,inspection_id,action_type,due_at,notes,created_by) values($1,$2,$3,$4,$5,$6,$7) returning *`,[input.operatorId,input.licenseId??null,input.inspectionId??null,input.actionType,input.dueAt??null,input.notes??null,input.createdBy]);if(r.rows[0])await this.pool.query(`insert into regulatory_status_events(entity_type,entity_id,to_status,changed_by,metadata) values('compliance_action',$1,'open',$2,$3)`,[r.rows[0].id,input.createdBy,JSON.stringify({actionType:input.actionType})]);return r.rows[0];}
  async listComplianceActions(operatorId?:string,status?:string){const clauses:string[]=[];const params:unknown[]=[];if(operatorId){params.push(operatorId);clauses.push(`operator_id=$${params.length}`);}if(status){params.push(status);clauses.push(`status=$${params.length}`);}const r=await this.pool.query(`select * from regulatory_compliance_actions ${clauses.length?'where '+clauses.join(' and '):''} order by created_at desc`,params);return r.rows;}
  async transitionComplianceAction(input:{actionId:string;status:'open'|'in_progress'|'completed'|'cancelled';changedBy:string;notes?:string;reason?:string}){const current=await this.pool.query(`select status from regulatory_compliance_actions where id=$1`,[input.actionId]);if(!current.rows[0])return null;if(current.rows[0].status==='cancelled'&&input.status!=='cancelled')throw Object.assign(new Error('Cancelled compliance actions cannot be reopened'),{code:'VALIDATION_ERROR'});const r=await this.pool.query(`update regulatory_compliance_actions set status=$2,completed_at=case when $2='completed' then coalesce(completed_at,now()) else completed_at end,notes=coalesce($3,notes),updated_at=now() where id=$1 returning *`,[input.actionId,input.status,input.notes??null]);if(r.rows[0]&&current.rows[0].status!==input.status)await this.pool.query(`insert into regulatory_status_events(entity_type,entity_id,from_status,to_status,changed_by,reason) values('compliance_action',$1,$2,$3,$4,$5)`,[input.actionId,current.rows[0].status,input.status,input.changedBy,input.reason??input.notes??null]);await this.pool.query(`select regulatory_sync_operator_compliance()`);return r.rows[0]??null;}
  async regulatoryStatusHistory(entityType:'license'|'inspection'|'compliance_action',entityId:string){const r=await this.pool.query(`select * from regulatory_status_events where entity_type=$1 and entity_id=$2 order by changed_at desc`,[entityType,entityId]);return r.rows;}
  async regulatoryMaintenance(){const overdue=await this.pool.query(`select regulatory_mark_overdue_actions()::int affected`);const expired=await this.pool.query(`select regulatory_expire_licenses()::int affected`);const synced=await this.pool.query(`select regulatory_sync_operator_compliance()::int affected`);return {overdueActions:overdue.rows[0]?.affected??0,expiredLicenses:expired.rows[0]?.affected??0,operatorsSynced:synced.rows[0]?.affected??0};}
  async listPartners(status?:string){const r=await this.pool.query(`select p.*,coalesce(jsonb_agg(jsonb_build_object('channelCode',c.code,'channelName',c.name,'status',b.status)) filter (where c.id is not null),'[]') channels from distribution.partners p left join distribution.partner_channel_bindings b on b.partner_id=p.id left join distribution.channels c on c.id=b.channel_id ${status?'where p.status=$1':''} group by p.id order by p.created_at desc`,status?[status]:[]);return r.rows;}
  async upsertPartner(input:{code:string;name:string;partnerType?:string;endpointUrl?:string;capabilities?:Record<string,unknown>}){const r=await this.pool.query(`insert into distribution.partners(code,name,partner_type,endpoint_url,capabilities) values($1,$2,$3,$4,$5) on conflict(code) do update set name=excluded.name,partner_type=excluded.partner_type,endpoint_url=excluded.endpoint_url,capabilities=excluded.capabilities,updated_at=now() returning *`,[input.code,input.name,input.partnerType??'third_party',input.endpointUrl??null,JSON.stringify(input.capabilities??{})]);return r.rows[0];}
  async bindPartnerChannel(input:{partnerId:string;channelCode:string}){const r=await this.pool.query(`insert into distribution.partner_channel_bindings(partner_id,channel_id) select $1,id from distribution.channels where code=$2 on conflict(partner_id,channel_id) do update set status='active' returning partner_id,id from distribution.channels where code=$2`,[input.partnerId,input.channelCode]);return r.rows[0]??null;}
}
