import { createHmac, timingSafeEqual } from 'node:crypto';
import type { ProvinceCode } from '../domain/types';
import type { OfflineChannel, OfflineManifest, OfflineRecord, QrHandoff, SyncState } from '../domain/offline';
import type { ContentRepository, DestinationRepository } from './contracts';
export interface OfflineServiceDeps { destinations: DestinationRepository; content: ContentRepository; }
export interface OfflineManifestOptions { channel: OfflineChannel; provinceCode?: ProvinceCode; limit?: number; now?: Date; }
const DEFAULT_STALE_AFTER_SECONDS=24*60*60;
const DEFAULT_QR_TTL_SECONDS=30*24*60*60;

export class OfflineService {
  constructor(private readonly deps:OfflineServiceDeps, private readonly verificationSecret=process.env.AUTH_JWT_SECRET||''){}
  async buildManifest(options:OfflineManifestOptions):Promise<OfflineManifest>{if(options.channel==='provincial'&&!options.provinceCode)throw new Error('Province code is required for provincial offline manifests');const limit=Math.min(Math.max(options.limit??500,1),1000);const now=options.now??new Date();const provinceCode=options.channel==='provincial'?options.provinceCode:undefined;const [destinations,content]=await Promise.all([this.deps.destinations.list({provinceCode,limit}),this.deps.content.list({publicationStatus:'published',provinceCode,limit})]);const records:OfflineRecord[]=[...destinations.items.filter((item)=>item.publicationStatus==='published'&&(!provinceCode||item.provinceCode===provinceCode)).map((item)=>({id:item.id,kind:'destination' as const,version:`${item.id}:${item.contentVersion}`,updatedAt:item.updatedAt,payload:item})),...content.items.filter((item)=>item.publicationStatus==='published'&&(!provinceCode||item.provinceCode===provinceCode)).map((item)=>({id:item.id,kind:'content' as const,version:`${item.id}:${item.version}`,updatedAt:item.updatedAt,payload:item}))];return {schemaVersion:1,generatedAt:now.toISOString(),channel:options.channel,...(provinceCode?{provinceCode}:{}),records,source:'public-published-content'};}
  syncState(lastSuccessfulSyncAt?:string,now=new Date(),staleAfterSeconds=DEFAULT_STALE_AFTER_SECONDS):SyncState{if(!lastSuccessfulSyncAt)return {health:'never_synced',staleAfterSeconds};const ageSeconds=Math.max(0,(now.getTime()-new Date(lastSuccessfulSyncAt).getTime())/1000);return {health:ageSeconds>staleAfterSeconds?'stale':'fresh',lastSuccessfulSyncAt,staleAfterSeconds};}
  offlineState(lastSuccessfulSyncAt?:string,_now=new Date(),staleAfterSeconds=DEFAULT_STALE_AFTER_SECONDS):SyncState{return {health:'offline',...(lastSuccessfulSyncAt?{lastSuccessfulSyncAt}:{}),staleAfterSeconds};}
  createQrHandoff(targetType:QrHandoff['targetType'],targetId:string,expiresAt=new Date(Date.now()+DEFAULT_QR_TTL_SECONDS*1000)):QrHandoff{if(!targetId.trim())throw new Error('QR handoff target is required');const payload=`1|${targetType}|${targetId}|${expiresAt.toISOString()}`;const signature=this.sign(payload);const verificationToken=`${toBase64Url(payload)}.${signature}`;return {version:1,targetType,targetId,uri:`pngtourism://handoff/${targetType}/${encodeURIComponent(targetId)}?verification=${encodeURIComponent(verificationToken)}`,expiresAt:expiresAt.toISOString(),verificationToken};}
  verifyQrHandoff(token:string):{targetType:'destination'|'content';targetId:string;expiresAt:string}{if(!this.verificationSecret)throw new Error('QR verification is not configured');const [encoded,signature]=token.split('.');if(!encoded||!signature)throw new Error('Invalid QR verification token');const payload=fromBase64Url(encoded);const expected=this.sign(payload);const a=Buffer.from(signature);const b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))throw new Error('Invalid QR verification signature');const [version,targetType,targetId,expiresAt]=payload.split('|');if(version!=='1'||(targetType!=='destination'&&targetType!=='content')||!targetId||!expiresAt)throw new Error('Invalid QR verification payload');if(new Date(expiresAt).getTime()<=Date.now())throw new Error('QR verification token expired');return {targetType,targetId,expiresAt};}
  private sign(payload:string){return createHmac('sha256',this.verificationSecret).update(payload).digest('base64url');}
}
function toBase64Url(value:string){return Buffer.from(value,'utf8').toString('base64url');}
function fromBase64Url(value:string){return Buffer.from(value,'base64url').toString('utf8');}
