import { describe, expect, it } from 'vitest';
import { OfflineService } from './offline-service';

const destination={id:'dest-1',name:'Kokoda',slug:'kokoda',provinceCode:'ORO',description:'Track',latitude:-8,longitude:147,publicationStatus:'published',updatedAt:'2026-09-09T00:00:00.000Z',contentVersion:3};
const content={id:'content-1',type:'experience',title:'Kokoda Experience',slug:'kokoda-experience',provinceCode:'ORO',summary:'Walk the track',body:'Guided experience',publicationStatus:'published',publishedAt:'2026-09-09T00:00:00.000Z',publicationSource:'tpa',updatedAt:'2026-09-09T00:00:00.000Z',version:2};
function deps(){return {destinations:{list:async()=>({items:[destination],nextCursor:undefined}),getById:async()=>destination,create:async()=>destination},content:{list:async()=>({items:[content],nextCursor:undefined}),getById:async()=>content,create:async()=>content,setPublication:async()=>content}} as any;}
function required(value:string|undefined,name:string):string{if(!value)throw new Error(`Expected ${name}`);return value;}

describe('OfflineService public delivery',()=>{
 it('builds province-scoped published manifests with stable versions and timestamps',async()=>{const service=new OfflineService(deps());const manifest=await service.buildManifest({channel:'provincial',provinceCode:'ORO',now:new Date('2026-09-09T12:00:00.000Z')});expect(manifest.source).toBe('public-published-content');expect(manifest.provinceCode).toBe('ORO');expect(manifest.records.map(r=>r.version)).toEqual(['dest-1:3','content-1:2']);expect(manifest.records.every(r=>r.updatedAt==='2026-09-09T00:00:00.000Z')).toBe(true);});
 it('requires province for provincial channel and rejects empty QR targets',async()=>{const service=new OfflineService(deps());await expect(service.buildManifest({channel:'provincial'} as any)).rejects.toThrow('Province code is required');expect(()=>service.createQrHandoff('destination','   ')).toThrow('QR handoff target is required');});
 it('creates a versioned verified deep-link handoff',()=>{const service=new OfflineService(deps());const handoff=service.createQrHandoff('content','content-1');const token=required(handoff.verificationToken,'QR verification token');const uri=required(handoff.uri,'QR handoff URI');const expiresAt=required(handoff.expiresAt,'QR expiry');expect(handoff.version).toBe(1);expect(handoff.targetType).toBe('content');expect(handoff.targetId).toBe('content-1');expect(token).toEqual(expect.any(String));expect(expiresAt).toEqual(expect.any(String));expect(uri).toContain('pngtourism://handoff/content/content-1?verification=');});
 it('verifies signed destination tokens and rejects tampering or expiry',()=>{const service=new OfflineService(deps(),'passport-test-secret');const handoff=service.createQrHandoff('destination','dest-1',new Date(Date.now()+60_000));const token=required(handoff.verificationToken,'QR verification token');const expiresAt=required(handoff.expiresAt,'QR expiry');expect(service.verifyQrHandoff(token)).toEqual(expect.objectContaining({targetType:'destination',targetId:'dest-1',expiresAt}));const [encoded,signature]=token.split('.');if (!encoded || !signature) throw new Error('Expected signed QR verification token');const tampered=`${encoded.slice(0,-1)}${encoded.endsWith('A')?'B':'A'}.${signature}`;expect(()=>service.verifyQrHandoff(tampered)).toThrow('Invalid QR verification signature');const expired=service.createQrHandoff('destination','dest-1',new Date(Date.now()-1_000));const expiredToken=required(expired.verificationToken,'expired QR verification token');expect(()=>service.verifyQrHandoff(expiredToken)).toThrow('QR verification token expired');});
});
