import { useEffect, useState } from 'react';
import { Activity, Building2, Compass, RefreshCw, Users, type LucideIcon } from 'lucide-react';

type ProvinceInsight = { provinceCode: string; publishedDestinations: number; activeOperators: number; compliantOperators: number; publishedExperiences: number; visitorSignals: number; engagementSignals: number };
type Report = { generatedAt: string; period: string; snapshot: { visitors: number; publishedDestinations: number; activeOperators: number; compliantOperators: number; publishedExperiences: number; provincesRepresented: number }; engagement: { totalSignals: number; experienceViews: number; savedExperiences: number; itineraryAdds: number; qrHandoffs: number }; provinces: ProvinceInsight[]; freshness: { source: string; generatedAt: string; governed: true }[] };
type MetricCard = { label: string; value: number; Icon: LucideIcon };

const periods = ['day', 'week', 'month', 'quarter', 'year'];
export default function CommandCentre() {
  const [period, setPeriod] = useState('month'); const [province, setProvince] = useState(''); const [report, setReport] = useState<Report | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const qs = new URLSearchParams({ period }); if (province) qs.set('province', province); const response = await fetch(`/api/v1/command-centre/report?${qs}`); if (!response.ok) throw new Error('Unable to load Command Centre data'); const body = await response.json(); setReport(body.data); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load Command Centre data'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [period, province]);
  const snapshot = report?.snapshot;
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-semibold uppercase tracking-wider text-emerald-700">TPA Operations</div><h2 className="mt-1 text-3xl font-bold tracking-tight">Command Centre</h2><p className="mt-2 max-w-3xl text-slate-600">Governed national and provincial tourism signals from platform operations and approved visitor engagement telemetry.</p></div><div className="flex flex-wrap gap-2"><select value={period} onChange={e => setPeriod(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm">{periods.map(p => <option key={p}>{p}</option>)}</select><select value={province} onChange={e => setProvince(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">All provinces</option>{report?.provinces.map(p => <option key={p.provinceCode} value={p.provinceCode}>{p.provinceCode}</option>)}</select><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm font-semibold"><RefreshCw size={15}/> Refresh</button></div></div>
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {loading && <div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Loading governed intelligence…</div>}
    {!loading && report && <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{([['Published destinations',snapshot!.publishedDestinations,Compass],['Active operators',snapshot!.activeOperators,Building2],['Compliant operators',snapshot!.compliantOperators,Users],['Published experiences',snapshot!.publishedExperiences,Activity]] as MetricCard[]).map(({label,value,Icon}) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">{label}</span><Icon size={18} className="text-emerald-700"/></div><div className="mt-2 text-3xl font-bold">{value}</div></div>)}</div>
    <div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><h3 className="font-bold">Provincial performance</h3><p className="mt-1 text-xs text-slate-500">Published supply, operator health and engagement signals.</p></div></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Province</th><th className="pb-3">Destinations</th><th className="pb-3">Operators</th><th className="pb-3">Experiences</th><th className="pb-3">Signals</th></tr></thead><tbody>{report.provinces.map(p => <tr key={p.provinceCode} className="border-t border-slate-100"><td className="py-3 font-semibold">{p.provinceCode}</td><td className="py-3">{p.publishedDestinations}</td><td className="py-3">{p.activeOperators} <span className="text-xs text-slate-400">({p.compliantOperators} compliant)</span></td><td className="py-3">{p.publishedExperiences}</td><td className="py-3 font-semibold">{p.engagementSignals}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">Visitor engagement</h3><div className="mt-5 space-y-4">{[['Total signals',report.engagement.totalSignals],['Experience views',report.engagement.experienceViews],['Saved experiences',report.engagement.savedExperiences],['Itinerary additions',report.engagement.itineraryAdds],['QR handoffs',report.engagement.qrHandoffs]].map(([label,value]) => <div key={String(label)} className="flex items-center justify-between border-b border-slate-100 pb-3"><span className="text-sm text-slate-600">{label}</span><span className="font-bold">{value as number}</span></div>)}</div></section></div>
    <div className="flex flex-wrap gap-3 text-xs text-slate-500"><span>Generated {new Date(report.generatedAt).toLocaleString()}</span><span>•</span><span>{snapshot!.provincesRepresented} provinces represented</span><span>•</span><span>Visitor counts remain unpopulated until an approved visitor-count source is available.</span></div></>}
  </div>;
}
