import type { Pool } from 'pg';
import type { ProvinceCode } from '../domain/types';
import type { IndustryExperience, IndustryProfile, IndustryRepository, VisitorLead } from '../domain/industry-ecosystem';

const province = (v: string) => v as ProvinceCode;
const iso = (v: Date | string) => new Date(v).toISOString();

export class PostgresIndustryRepository implements IndustryRepository {
  constructor(private readonly pool: Pool) {}
  async getProfile(operatorId: string) { const r=await this.pool.query('select * from industry_profiles where operator_id=$1',[operatorId]); return r.rows[0]?profile(r.rows[0]):null; }
  async saveProfile(p: IndustryProfile, expectedVersion?: number) { const values:any[]=[p.id,p.operatorId,p.displayName,p.description,p.provinceCode,p.categories,p.publicContact?.website??null,p.publicContact?.email??null,p.publicContact?.phone??null,p.published,p.version,p.updatedAt]; const guard=expectedVersion===undefined?'':' and version=$13'; if(expectedVersion!==undefined)values.push(expectedVersion); const q=`insert into industry_profiles(id,operator_id,display_name,description,province_code,categories,website,public_email,public_phone,published,version,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) on conflict (id) do update set display_name=$3,description=$4,province_code=$5,categories=$6,website=$7,public_email=$8,public_phone=$9,published=$10,version=$11,updated_at=$12 where industry_profiles.version=${expectedVersion===undefined?'industry_profiles.version':'$13'} returning *`; const r=await this.pool.query(q,values); return r.rows[0]?profile(r.rows[0]):null; }
  async listPublishedProfiles(options:any={}) { const v:any=[],w=['published=true']; if(options.provinceCode){v.push(options.provinceCode);w.push(`province_code=$${v.length}`)} v.push(Math.min(Math.max(options.limit??50,1),100)); const r=await this.pool.query(`select * from industry_profiles where ${w.join(' and ')} order by display_name limit $${v.length}`,v); return r.rows.map(profile); }
  async getExperience(id:string){const r=await this.pool.query('select * from industry_experiences where id=$1',[id]);return r.rows[0]?experience(r.rows[0]):null;}
  async saveExperience(e:IndustryExperience,expectedVersion?:number){const v:any[]=[e.id,e.operatorId,e.title,e.summary,e.destinationId??null,e.provinceCode,e.status,e.version,e.updatedAt];if(expectedVersion!==undefined)v.push(expectedVersion);const r=await this.pool.query(`insert into industry_experiences(id,operator_id,title,summary,destination_id,province_code,status,version,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(id) do update set title=$3,summary=$4,destination_id=$5,province_code=$6,status=$7,version=$8,updated_at=$9 where industry_experiences.version=${expectedVersion===undefined?'industry_experiences.version':'$10'} returning *`,v);return r.rows[0]?experience(r.rows[0]):null;}
  async listPublishedExperiences(options:any={}){const v:any=[],w=["status='published'"];if(options.provinceCode){v.push(options.provinceCode);w.push(`province_code=$${v.length}`)}if(options.destinationId){v.push(options.destinationId);w.push(`destination_id=$${v.length}`)}v.push(Math.min(Math.max(options.limit??50,1),100));const r=await this.pool.query(`select * from industry_experiences where ${w.join(' and ')} order by title limit $${v.length}`,v);return r.rows.map(experience);}
  async createLead(l:VisitorLead){const r=await this.pool.query('insert into visitor_leads(id,operator_id,experience_id,source,status,visitor_message,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[l.id,l.operatorId,l.experienceId??null,l.source,l.status,l.visitorMessage??null,l.createdAt,l.updatedAt]);return lead(r.rows[0]);}
  async listLeads(operatorId:string){const r=await this.pool.query('select * from visitor_leads where operator_id=$1 order by created_at desc',[operatorId]);return r.rows.map(lead);}
}
function profile(r:any):IndustryProfile{return{id:r.id,operatorId:r.operator_id,displayName:r.display_name,description:r.description,provinceCode:province(r.province_code),categories:r.categories??[],publicContact:{...(r.website?{website:r.website}:{}),...(r.public_email?{email:r.public_email}:{}),...(r.public_phone?{phone:r.public_phone}:{})},published:r.published,updatedAt:iso(r.updated_at),version:Number(r.version)}}
function experience(r:any):IndustryExperience{return{id:r.id,operatorId:r.operator_id,title:r.title,summary:r.summary,destinationId:r.destination_id??undefined,provinceCode:province(r.province_code),status:r.status,updatedAt:iso(r.updated_at),version:Number(r.version)}}
function lead(r:any):VisitorLead{return{id:r.id,operatorId:r.operator_id,experienceId:r.experience_id??undefined,source:r.source,status:r.status,visitorMessage:r.visitor_message??undefined,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)}}
