import type { Pool } from 'pg';
import type { ProvinceCode } from '../domain/types';
import type { IndustryExperience, IndustryProfile, IndustryRepository, VisitorLead } from '../domain/industry-ecosystem';

const asProvince = (value: string) => value as ProvinceCode;
const iso = (value: Date | string) => new Date(value).toISOString();

export class PostgresIndustryRepository implements IndustryRepository {
  constructor(private readonly pool: Pool) {}
  async getProfile(operatorId: string) { const r = await this.pool.query('select * from industry_profiles where operator_id=$1',[operatorId]); return r.rows[0] ? toProfile(r.rows[0]) : null; }
  async saveProfile(p: IndustryProfile, expectedVersion?: number) { const values:any[]=[p.id,p.operatorId,p.displayName,p.description,p.provinceCode,p.categories,p.publicContact?.website??null,p.publicContact?.email??null,p.publicContact?.phone??null,p.published,p.reviewStatus,p.version,p.updatedAt]; if(expectedVersion!==undefined) values.push(expectedVersion); const r=await this.pool.query(`insert into industry_profiles(id,operator_id,display_name,description,province_code,categories,website,public_email,public_phone,published,review_status,version,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) on conflict(id) do update set display_name=$3,description=$4,province_code=$5,categories=$6,website=$7,public_email=$8,public_phone=$9,published=$10,review_status=$11,version=$12,updated_at=$13 where industry_profiles.version=${expectedVersion===undefined?'industry_profiles.version':'$14'} returning *`,values); return r.rows[0] ? toProfile(r.rows[0]) : null; }
  async listPublishedProfiles(options:{provinceCode?:ProvinceCode;limit?:number}={}) { const values:any[]=[]; const where=["ip.published=true","ip.review_status='published'","o.status='active'"]; if(options.provinceCode){values.push(options.provinceCode);where.push(`ip.province_code=$${values.length}`)} values.push(Math.min(Math.max(options.limit??50,1),100)); const r=await this.pool.query(`select ip.* from industry_profiles ip join operators o on o.id=ip.operator_id where ${where.join(' and ')} order by ip.display_name limit $${values.length}`,values); return r.rows.map(toProfile); }
  async getExperience(id:string) { const r=await this.pool.query('select * from industry_experiences where id=$1',[id]); return r.rows[0] ? toExperience(r.rows[0]) : null; }
  async saveExperience(e:IndustryExperience, expectedVersion?:number) { const values:any[]=[e.id,e.operatorId,e.title,e.summary,e.destinationId??null,e.provinceCode,e.status,e.version,e.updatedAt]; if(expectedVersion!==undefined) values.push(expectedVersion); const r=await this.pool.query(`insert into industry_experiences(id,operator_id,title,summary,destination_id,province_code,status,version,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(id) do update set title=$3,summary=$4,destination_id=$5,province_code=$6,status=$7,version=$8,updated_at=$9 where industry_experiences.version=${expectedVersion===undefined?'industry_experiences.version':'$10'} returning *`,values); return r.rows[0] ? toExperience(r.rows[0]) : null; }
  async listPublishedExperiences(options:{provinceCode?:ProvinceCode;destinationId?:string;limit?:number}={}) { const values:any[]=[]; const where=["ie.status='published'","o.status='active'"]; if(options.provinceCode){values.push(options.provinceCode);where.push(`ie.province_code=$${values.length}`)} if(options.destinationId){values.push(options.destinationId);where.push(`ie.destination_id=$${values.length}`)} values.push(Math.min(Math.max(options.limit??50,1),100)); const r=await this.pool.query(`select ie.* from industry_experiences ie join operators o on o.id=ie.operator_id where ${where.join(' and ')} order by ie.title limit $${values.length}`,values); return r.rows.map(toExperience); }
  async createLead(l:VisitorLead) { const r=await this.pool.query('insert into visitor_leads(id,operator_id,experience_id,source,status,visitor_message,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[l.id,l.operatorId,l.experienceId??null,l.source,l.status,l.visitorMessage??null,l.createdAt,l.updatedAt]); return toLead(r.rows[0]); }
  async listLeads(operatorId:string) { const r=await this.pool.query('select * from visitor_leads where operator_id=$1 order by created_at desc',[operatorId]); return r.rows.map(toLead); }
}
function toProfile(r:any):IndustryProfile{return{id:r.id,operatorId:r.operator_id,displayName:r.display_name,description:r.description,provinceCode:asProvince(r.province_code),categories:r.categories??[],publicContact:{...(r.website?{website:r.website}:{}),...(r.public_email?{email:r.public_email}:{}),...(r.public_phone?{phone:r.public_phone}:{})},published:r.published,reviewStatus:r.review_status??(r.published?'published':'draft'),updatedAt:iso(r.updated_at),version:Number(r.version)}}
function toExperience(r:any):IndustryExperience{return{id:r.id,operatorId:r.operator_id,title:r.title,summary:r.summary,destinationId:r.destination_id??undefined,provinceCode:asProvince(r.province_code),status:r.status,updatedAt:iso(r.updated_at),version:Number(r.version)}}
function toLead(r:any):VisitorLead{return{id:r.id,operatorId:r.operator_id,experienceId:r.experience_id??undefined,source:r.source,status:r.status,visitorMessage:r.visitor_message??undefined,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)}}
