import { useEffect, useState } from 'react';
import { Building2, CheckCircle2, FileText, Plus, Send, ShieldCheck } from 'lucide-react';

type Profile={id:string;operatorId:string;displayName:string;description:string;provinceCode:string;categories:string[];publicContact?:{website?:string;email?:string;phone?:string};published:boolean;version:number};
type Experience={id:string;operatorId:string;title:string;summary:string;destinationId?:string;provinceCode:string;status:'draft'|'submitted'|'published'|'suspended';version:number};

export default function OperatorWorkspace(){
  const [operatorId,setOperatorId]=useState(''); const [profile,setProfile]=useState<Profile|null>(null); const [experiences,setExperiences]=useState<Experience[]>([]); const [title,setTitle]=useState(''); const [summary,setSummary]=useState(''); const [destinationId,setDestinationId]=useState(''); const [status,setStatus]=useState(''); const [error,setError]=useState('');
  const api=async(path:string,init?:RequestInit)=>{const r=await fetch(path,init);const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error?.message||'Request failed');return b.data;};
  const load=async()=>{if(!operatorId.trim())return;setError('');try{const p=await api(`/api/v1/industry/profiles/${encodeURIComponent(operatorId)}`);setProfile(p);const list:Experience[]=[];setExperiences(list);setStatus(p?'Profile loaded.':'No profile yet — create one below.');}catch(e){setProfile(null);setExperiences([]);setError(e instanceof Error?e.message:'Unable to load operator workspace.');}};
  useEffect(()=>{const q=new URLSearchParams(window.location.search).get('operatorId');if(q){setOperatorId(q);void (async()=>{try{const p=await api(`/api/v1/industry/profiles/${encodeURIComponent(q)}`);setProfile(p);setStatus(p?'Profile loaded.':'No profile yet — create one below.');}catch(e){setError(e instanceof Error?e.message:'Unable to load operator workspace.');}})();}},[]);
  const saveProfile=async()=>{if(!profile&& !operatorId.trim())return;setError('');try{const p=await api(`/api/v1/industry/profiles/${encodeURIComponent(operatorId)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName:profile?.displayName||'Tourism operator',description:profile?.description||'Add your approved tourism business description.',categories:profile?.categories||[],publicContact:profile?.publicContact||{},version:profile?.version})});setProfile(p);setStatus('Profile saved as private draft. Submit it for TPA review when ready.');}catch(e){setError(e instanceof Error?e.message:'Unable to save profile.');}};
  const submitProfile=async()=>{try{const p=await api(`/api/v1/industry/profiles/${encodeURIComponent(operatorId)}/submit`,{method:'POST'});setProfile(p);setStatus('Profile submitted for TPA review.');}catch(e){setError(e instanceof Error?e.message:'Unable to submit profile.');}};
  const createExperience=async()=>{try{const e=await api('/api/v1/industry/experiences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operatorId,title,summary,destinationId:destinationId||undefined})});setExperiences(v=>[e,...v]);setTitle('');setSummary('');setDestinationId('');setStatus('Experience saved as draft.');}catch(e){setError(e instanceof Error?e.message:'Unable to create experience.');}};
  const updateExperience=async(e:Experience,next:'draft'|'submitted')=>{try{const updated=await api(`/api/v1/industry/experiences/${encodeURIComponent(e.id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...e,status:next,version:e.version})});setExperiences(v=>v.map(x=>x.id===e.id?updated:x));setStatus(next==='submitted'?'Experience submitted for TPA review.':'Draft updated.');}catch(err){setError(err instanceof Error?err.message:'Unable to update experience.');}};
  return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:p-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Industry workspace</div><h2 className="mt-1 text-2xl font-bold">Operator Workspace</h2><p className="mt-2 max-w-2xl text-sm text-slate-600">Manage your tourism profile and prepare experiences for governed TPA review. Published content is never self-published.</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={16}/> Approval and compliance remain TPA-controlled</div></div>
    <div className="mt-6 rounded-2xl bg-slate-50 p-4"><label className="text-xs font-bold uppercase tracking-wide text-slate-500">Authenticated operator context</label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input value={operatorId} onChange={e=>setOperatorId(e.target.value)} placeholder="Operator ID" className="min-w-0 flex-1 rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"/><button onClick={()=>void load()} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Load workspace</button></div><p className="mt-2 text-xs text-slate-500">Production identity must resolve to this operator through the authenticated session; the ID field is retained for controlled administration and development.</p></div>
    {error&&<div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}{status&&<div role="status" className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">{status}</div>}
    {operatorId&&<div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center gap-2 font-bold"><Building2 size={18}/> Business profile</div><div className="mt-4 space-y-3"><input value={profile?.displayName||''} onChange={e=>setProfile(p=>p?{...p,displayName:e.target.value}:({id:'',operatorId,displayName:e.target.value,description:'',provinceCode:'',categories:[],version:1,published:false}))} placeholder="Public business name" className="w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"/><textarea value={profile?.description||''} onChange={e=>setProfile(p=>p?{...p,description:e.target.value}:({id:'',operatorId,displayName:'',description:e.target.value,provinceCode:'',categories:[],version:1,published:false}))} placeholder="Describe your approved tourism business" rows={5} className="w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"/><div className="flex flex-wrap gap-2"><button onClick={()=>void saveProfile()} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white"><FileText size={15}/> Save draft</button><button disabled={!profile?.id} onClick={()=>void submitProfile()} className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 px-4 py-2 text-sm font-semibold text-emerald-700"><Send size={15}/> Submit for review</button></div></div></div>
      <div className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center gap-2 font-bold"><Plus size={18}/> New experience</div><div className="mt-4 space-y-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Experience title" className="w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"/><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Experience summary" rows={4} className="w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"/><input value={destinationId} onChange={e=>setDestinationId(e.target.value)} placeholder="Destination ID (optional)" className="w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"/><button disabled={!title.trim()||!summary.trim()} onClick={()=>void createExperience()} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white"><Plus size={15}/> Create draft</button></div><div className="mt-6 border-t border-slate-100 pt-5"><h3 className="font-bold">Workspace experiences</h3>{experiences.length===0?<p className="mt-3 text-sm text-slate-500">Load an existing experience list through the authenticated workspace session.</p>:<div className="mt-3 space-y-3">{experiences.map(e=><div key={e.id} className="rounded-xl border border-slate-200 p-3"><div className="font-semibold">{e.title}</div><div className="mt-1 text-xs text-slate-500">{e.status} · v{e.version}</div>{e.status==='draft'&&<button onClick={()=>void updateExperience(e,'submitted')} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-emerald-200 px-3 py-1.5 text-xs font-semibold text-emerald-700"><CheckCircle2 size={14}/> Submit for review</button>}</div>)}</div>}</div></div>
    </div>}
  </section>;
}
