import { useEffect, useState } from 'react';

type Item = { id: string; type: 'event' | 'campaign'; title: string; slug: string; provinceCode?: string; summary?: string; publicationStatus: string; updatedAt: string };
const tabs = ['event', 'campaign'] as const;
export default function ActivationHub() {
  const [type, setType] = useState<(typeof tabs)[number]>('event'); const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const r = await fetch(`/api/v1/${type}s`); if (!r.ok) throw new Error('Unable to load activation records'); const b = await r.json(); setItems(b.data || []); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load activation records'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [type]);
  const publish = async (id: string) => { const r = await fetch(`/api/v1/${type}s/${encodeURIComponent(id)}/publish`, { method: 'POST' }); if (!r.ok) { setError('Unable to publish activation'); return; } void load(); };
  return <div className="space-y-6"><div><div className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Content activation</div><h2 className="mt-1 text-3xl font-bold tracking-tight">Campaigns & events</h2><p className="mt-2 max-w-3xl text-slate-600">Manage governed tourism activations that can be published to visitor channels, provincial experiences and QR handoffs.</p></div><div className="flex gap-2">{tabs.map(t => <button key={t} onClick={() => setType(t)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${type === t ? 'bg-emerald-700 text-white' : 'border border-slate-300 bg-white text-slate-600'}`}>{t === 'event' ? 'Events' : 'Campaigns'}</button>)}<button onClick={() => void load()} className="ml-auto rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Refresh</button></div>{error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{loading ? <div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Loading activation records…</div> : <div className="grid gap-4 md:grid-cols-2">{items.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-500">No {type}s are available yet.</div> : items.map(item => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-400">{item.provinceCode || 'National'} · {item.publicationStatus}</div><h3 className="mt-1 font-bold">{item.title}</h3></div>{item.publicationStatus === 'review' && <button onClick={() => void publish(item.id)} className="rounded-xl bg-emerald-700 px-3 py-2 text-xs font-semibold text-white">Publish</button>}</div><p className="mt-3 text-sm leading-6 text-slate-600">{item.summary || 'No summary supplied.'}</p><div className="mt-4 text-xs text-slate-400">Updated {new Date(item.updatedAt).toLocaleString()}</div></article>)}</div>}</div>;
}
