insert into public.provinces (code, name, slug) values ('ORO','Oro Province','oro'), ('MILNE_BAY','Milne Bay Province','milne-bay'), ('EAST_NEW_BRITAIN','East New Britain Province','east-new-britain'), ('EAST_SEPIK','East Sepik Province','east-sepik'), ('WESTERN_HIGHLANDS','Western Highlands Province','western-highlands') on conflict (code) do update set name=excluded.name, slug=excluded.slug;

insert into public.destinations (name, slug, province_code, publication_status, description, latitude, longitude, content_version) values
('Kokoda Track','kokoda-track','ORO','published','The Kokoda Track is one of Papua New Guinea’s most iconic trekking routes, following historic mountain trails through the rugged Owen Stanley Range and rainforest between the Kokoda area and the Central Province.',-9.058,147.735,1),
('Milne Bay','milne-bay','MILNE_BAY','published','Milne Bay offers spectacular island landscapes, coral reefs, rich marine life and traditional coastal communities across the far southeastern corner of Papua New Guinea.',-10.316,150.457,1),
('Rabaul','rabaul','EAST_NEW_BRITAIN','published','Rabaul is a dramatic volcanic destination on the Gazelle Peninsula, known for its harbour, wartime history, volcanic landscapes and access to the islands and waters of East New Britain.',-4.198,152.172,1),
('Sepik River','sepik-river','EAST_SEPIK','published','The Sepik River is one of Papua New Guinea’s great cultural and natural journeys, with river communities, distinctive artistic traditions, wetlands and remote villages along its winding course.',-4.200,143.500,1),
('Western Highlands','western-highlands','WESTERN_HIGHLANDS','published','The Western Highlands combines high mountain valleys, rich agricultural landscapes and living cultural traditions, with access to the Highlands around Mount Hagen.',-5.857,144.229,1)
on conflict (slug) do update set name=excluded.name, province_code=excluded.province_code, publication_status=excluded.publication_status, description=excluded.description, latitude=excluded.latitude, longitude=excluded.longitude, content_version=excluded.content_version, updated_at=now();
