import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Bot, Compass, MapPin, Menu, Search, ShieldCheck, Users, X } from 'lucide-react';
import tpaLogo from './assets/png-tpa-logo.png';
import DestinationExplorer from './visitor/DestinationExplorer';
import AiConcierge from './visitor/AiConcierge';
import VisitorIndustryTripIntegration from './visitor/VisitorIndustryTripIntegration';
import TripPlanner from './visitor/TripPlanner';
import DestinationDetail from './visitor/DestinationDetail';

type Props = { onAdmin: () => void };
type Destination = { id: string; name: string; province: string; description: string };
const heroImage = 'https://papuanewguinea.travel/wp-content/uploads/elementor/thumbs/What-To-Do-In-Milne-Bay-Province-rkffalz60frjn6vrj1z9zkwro2anrnpfia7ub30g4w.webp';
const fallback: Destination[] = [
  { id: 'kokoda', name: 'Kokoda Track', province: 'Oro Province', description: 'Walk in history. Experience the spirit of resilience.' },
  { id: 'milne-bay', name: 'Milne Bay', province: 'Milne Bay Province', description: 'World-class diving in the heart of the Pacific.' },
  { id: 'rabaul', name: 'Rabaul', province: 'East New Britain Province', description: 'History, culture and natural wonders.' },
  { id: 'sepik', name: 'Sepik River', province: 'East Sepik Province', description: 'Ancient cultures. Living traditions.' },
  { id: 'kumul-country', name: 'Kumul Country', province: 'Western Highlands', description: 'Spectacular landscapes. Unique wildlife.' },
];

export default function VisitorHome({ onAdmin }: Props) {
  const [mobileOpen, setMobileOpen] = useState(false); const [query, setQuery] = useState(''); const [destinations, setDestinations] = useState<Destination[]>(fallback); const [selectedDestination, setSelectedDestination] = useState<string | null>(null);
  useEffect(() => { fetch('/api/v1/public/destinations').then(r => r.ok ? r.json() : Promise.reject(new Error('unavailable'))).then(x => { const items = Array.isArray(x.data?.items) ? x.data.items : Array.isArray(x.data) ? x.data : []; if (items.length) setDestinations(items.slice(0, 5).map((d: any) => ({ id: d.id, name: d.name, province: d.provinceCode, description: d.description || 'Discover a published destination from Papua New Guinea.' }))); }).catch(() => undefined); }, []);
  const filtered = useMemo(() => destinations.filter(d => `${d.name} ${d.province} ${d.description}`.toLowerCase().includes(query.toLowerCase().trim())), [destinations, query]);
  const scroll = (id: string) => { setMobileOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  if (selectedDestination) return <div className="min-h-screen bg-[#f7f8f3] px-4 py-5 sm:px-6"><div className="mx-auto max-w-7xl"><button onClick={() => setSelectedDestination(null)} className="mb-5 text-sm font-bold text-[#31502a]">← Back to PNG</button><DestinationDetail destinationId={selectedDestination} onBack={() => setSelectedDestination(null)} /></div></div>;
  return <div className="min-h-screen bg-[#f7f8f3] text-[#1d2b20]">
    <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center gap-7 px-5 py-3 lg:px-10"><a href="#top" className="shrink-0"><img src={tpaLogo} alt="Papua New Guinea Tourism Promotion Authority" className="h-12 w-auto sm:h-14" /></a><nav className={`${mobileOpen ? 'absolute left-0 right-0 top-full flex' : 'hidden'} flex-col gap-1 border-b bg-white p-5 lg:static lg:flex lg:flex-row lg:items-center lg:border-0 lg:bg-transparent lg:p-0`}>{[['Destinations','destinations'],['Experiences','experiences'],['Plan Your Trip','trip'],['Digital Passport','passport'],['AI Concierge','concierge'],['About PNG','about']].map(([label,id]) => <button key={id} onClick={() => scroll(id)} className="px-3 py-2 text-sm font-semibold text-slate-700 hover:text-[#31502a]">{label}</button>)}</nav><div className="ml-auto flex items-center gap-2"><button onClick={() => scroll('destinations')} aria-label="Search destinations" className="hidden rounded-full p-2 text-slate-700 hover:bg-slate-100 sm:block"><Search size={20}/></button><button onClick={() => scroll('destinations')} className="hidden rounded-full bg-[#2f5c2c] px-5 py-2.5 text-sm font-bold text-white shadow-sm sm:block">Explore PNG <span className="ml-1">⌄</span></button><button onClick={() => setMobileOpen(v => !v)} className="rounded-xl p-2 lg:hidden" aria-label="Menu">{mobileOpen ? <X/> : <Menu/>}</button></div></div></header>
    <main id="top">
      <section className="relative min-h-[590px] overflow-hidden bg-[#0b4b5b]"><img src={heroImage} alt="Milne Bay, Papua New Guinea" className="absolute inset-0 h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-[#071b2a]/85 via-[#071b2a]/35 to-[#071b2a]/10" /><div className="absolute inset-0 bg-gradient-to-t from-[#071b2a]/45 via-transparent to-transparent" /><div className="relative mx-auto flex min-h-[590px] max-w-[1500px] items-end px-5 pb-16 pt-24 lg:px-20"><div className="max-w-4xl text-white"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/20 bg-black/20 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] backdrop-blur"><MapPin size={14}/> Milne Bay Province · The Last Frontier</div><h1 className="max-w-4xl text-5xl font-black leading-[.94] tracking-[-.04em] sm:text-6xl lg:text-8xl">Discover<br/>Papua New Guinea</h1><p className="mt-6 max-w-3xl text-lg font-medium leading-7 text-white/90 sm:text-xl">Extraordinary people. Breathtaking places. A million different journeys.</p><div className="mt-8 flex max-w-2xl overflow-hidden rounded-full bg-white p-1.5 shadow-2xl"><Search className="m-3 text-slate-500" size={20}/><input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && scroll('destinations')} placeholder="Search destinations, experiences or provinces..." className="min-w-0 flex-1 bg-transparent px-2 text-sm text-slate-800 outline-none sm:text-base"/><button onClick={() => scroll('destinations')} className="rounded-full bg-[#2f5c2c] px-6 py-3 text-sm font-black text-white sm:px-8">Search</button></div></div><div className="absolute right-5 top-1/2 hidden w-72 -translate-y-1/2 rounded-3xl border border-white/15 bg-[#092a3b]/80 p-5 text-white shadow-2xl backdrop-blur-xl xl:block">{[['Explore Destinations','From mountains to islands',MapPin,'destinations'],['Plan Your Journey','Build your PNG experience',Users,'trip'],['Digital Passport','Collect your journey moments',ShieldCheck,'passport'],['AI Concierge','Your PNG travel companion',Bot,'concierge']].map(([title,text,Icon,id]: any) => <button key={title} onClick={() => scroll(id)} className="flex w-full items-center gap-4 rounded-2xl p-3 text-left hover:bg-white/10"><span className="rounded-xl bg-white/10 p-2.5"><Icon size={22}/></span><span><span className="block text-sm font-bold">{title}</span><span className="mt-1 block text-xs text-slate-300">{text}</span></span></button>)}</div></div></section>
      <section id="destinations" className="mx-auto max-w-[1500px] px-5 py-14 lg:px-12 lg:py-20"><div className="flex items-end justify-between gap-5"><div><div className="text-xs font-black uppercase tracking-[.2em] text-[#6b8a5b]">Explore PNG</div><h2 className="mt-2 text-4xl font-black tracking-tight text-[#20351e] sm:text-5xl">Featured Destinations</h2></div><button onClick={() => document.getElementById('destination-explorer')?.scrollIntoView({behavior:'smooth'})} className="hidden items-center gap-2 text-sm font-black text-[#31502a] sm:inline-flex">View all destinations <ArrowRight size={17}/></button></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{filtered.map((d, i) => <button key={d.id} onClick={() => setSelectedDestination(d.id)} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className={`flex aspect-[1.35] items-end bg-gradient-to-br ${['from-emerald-800 via-teal-600 to-cyan-500','from-cyan-700 via-sky-500 to-blue-400','from-slate-700 via-emerald-600 to-lime-400','from-amber-800 via-orange-500 to-rose-400','from-green-900 via-lime-700 to-yellow-400'][i % 5]} p-4`}><span className="rounded-full bg-black/30 px-3 py-1 text-xs font-bold text-white backdrop-blur">{d.province}</span></div><div className="p-4"><h3 className="text-lg font-black text-[#20351e]">{d.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{d.description}</p></div></button>)}</div><div id="destination-explorer" className="mt-10"><DestinationExplorer onOpen={setSelectedDestination}/></div></section>
      <section id="experiences" className="bg-white px-5 py-16 lg:px-12"><div className="mx-auto max-w-[1500px]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><div className="text-xs font-black uppercase tracking-[.2em] text-[#6b8a5b]">Go beyond the postcard</div><h2 className="mt-3 text-4xl font-black tracking-tight text-[#20351e]">A million different ways to experience PNG.</h2><p className="mt-4 max-w-xl text-base leading-7 text-slate-600">Connect with published tourism experiences, local operators and the people who make every journey different.</p></div><VisitorIndustryTripIntegration/></div></div></section>
      <section id="trip" className="bg-[#f0f5ed] px-5 py-16 lg:px-12"><div className="mx-auto max-w-[1500px]"><TripPlanner/></div></section>
      <section id="concierge" className="bg-[#071b2a] px-5 py-16 text-white lg:px-12"><div className="mx-auto max-w-[1200px]"><div className="mb-8 max-w-2xl"><div className="text-xs font-black uppercase tracking-[.2em] text-[#8fd5c8]">Your digital travel companion</div><h2 className="mt-3 text-4xl font-black">Meet the PNG AI Concierge.</h2><p className="mt-3 text-slate-300">Ask questions, discover published places and experiences, and move from inspiration to itinerary without leaving the journey.</p></div><AiConcierge/></div></section>
      <section id="passport" className="bg-[#f7f8f3] px-5 py-16 lg:px-12"><div className="mx-auto max-w-[1200px] rounded-[2rem] bg-gradient-to-br from-[#315c2f] to-[#123f47] p-8 text-white shadow-2xl sm:p-12"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[.16em]"><ShieldCheck size={14}/> Digital Tourism Passport</div><h2 className="mt-4 text-4xl font-black">Collect the moments that make your journey yours.</h2><p className="mt-4 max-w-2xl leading-7 text-white/80">Keep your itinerary and visit records available offline. Verification remains explicit and governed.</p></div><div className="flex h-28 w-28 items-center justify-center rounded-3xl border border-white/15 bg-white/10"><Compass size={52}/></div></div></div></section>
      <section id="about" className="border-t bg-white px-5 py-12 lg:px-12"><div className="mx-auto flex max-w-[1500px] flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><img src={tpaLogo} alt="PNG Tourism Promotion Authority" className="h-16 w-auto"/><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">The national tourism platform connecting visitors, destinations, tourism businesses and trusted public information across Papua New Guinea.</p></div><button onClick={onAdmin} className="rounded-full border border-slate-300 px-5 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50">TPA Command Centre</button></div></section>
    </main>
  </div>;
}
